-- ref_controle : 108 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[ref_controle])
BEGIN
    INSERT INTO dbo.[ref_controle] ([vue], [code], [libelle], [genre], [condition_anomalie], [fondement], [ordre], [modifie_par], [modifie_le]) VALUES
        (N'v_controle_actif_sans_entite_liee',NULL,N'controle actif sans entite liee',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'1',NULL,NULL),
        (N'v_controle_actif_sans_valeur',NULL,N'controle actif sans valeur',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'2',NULL,NULL),
        (N'v_controle_annexe_333_1',N'C61',N'Tableau 333-1 de l''annexe rapproché de l''actif net réévalué',N'RAPPROCHEMENT',N'ecart <> 0',N'Règlement ANC 2021-09, article 333-1',N'3',NULL,NULL),
        (N'v_controle_annexe_334_2',N'C65',N'Tableau 334-2 des immeubles rapproché de la ligne du bilan',N'RAPPROCHEMENT',N'ecart <> 0',N'Règlement ANC 2021-09, article 334-2',N'4',NULL,NULL),
        (N'v_controle_annexe_335_10',N'C68',N'Tableau 335-10 rapproché de la ligne VI du compte de résultat',N'RAPPROCHEMENT',N'ecart <> 0',N'Règlement ANC 2021-09, article 335-10',N'5',NULL,NULL),
        (N'v_controle_annexe_335_12',N'C69',N'Tableau 335-12 : l''affecté rapproché du distribuable',N'RAPPROCHEMENT',N'affecte_resultat <> distribuable_resultat OR affecte_pmv <> distribuable_pmv',N'Règlement ANC 2021-09, article 335-12',N'6',NULL,NULL),
        (N'v_controle_appui_sur_texte_abroge',NULL,N'controle appui sur texte abroge',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'7',NULL,NULL),
        (N'v_controle_arrete_date',NULL,N'controle arrete date',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'8',NULL,NULL),
        (N'v_controle_arrete_exercice',NULL,N'controle arrete exercice',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'9',NULL,NULL),
        (N'v_controle_arrete_hors_dimension',NULL,N'controle arrete hors dimension',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'10',NULL,NULL),
        (N'v_controle_aucun_associe',NULL,N'controle aucun associe',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'11',NULL,NULL),
        (N'v_controle_axe_manquant',NULL,N'controle axe manquant',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'12',NULL,NULL),
        (N'v_controle_balance_sans_import',NULL,N'controle balance sans import',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'13',NULL,NULL),
        (N'v_controle_bilan_desequilibre',NULL,N'controle bilan desequilibre',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'14',NULL,NULL),
        (N'v_controle_bornes_curseur',NULL,N'controle bornes curseur',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'15',NULL,NULL),
        (N'v_controle_classe_rattachement',NULL,N'controle classe rattachement',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'16',NULL,NULL),
        (N'v_controle_classement_interet',NULL,N'controle classement interet',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'17',NULL,NULL),
        (N'v_controle_cle_arrete',NULL,N'controle cle arrete',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'18',NULL,NULL),
        (N'v_controle_cle_ecran',NULL,N'controle cle ecran',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'107',NULL,NULL),
        (N'v_controle_cle_montant',NULL,N'controle cle montant',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'19',NULL,NULL),
        (N'v_controle_collision_512',NULL,N'controle collision 512',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'20',NULL,NULL),
        (N'v_controle_compte_deux_lignes',NULL,N'controle compte deux lignes',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'21',NULL,NULL),
        (N'v_controle_compte_estimation_absent',NULL,N'controle compte estimation absent',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'22',NULL,NULL),
        (N'v_controle_compte_estimation_inconnu',NULL,N'controle compte estimation inconnu',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'23',NULL,NULL),
        (N'v_controle_compte_hors_modele',NULL,N'controle compte hors modele',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'24',NULL,NULL),
        (N'v_controle_compte_hors_plan_entite',NULL,N'controle compte hors plan entite',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'91',NULL,NULL),
        (N'v_controle_concordance_articles',NULL,N'controle concordance articles',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'25',NULL,NULL),
        (N'v_controle_contrepartie_sans_reference',NULL,N'controle contrepartie sans reference',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'26',NULL,NULL),
        (N'v_controle_correspondance_sans_fondement',NULL,N'controle correspondance sans fondement',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'27',NULL,NULL),
        (N'v_controle_couple_incomplet',N'C51',N'Comptes courants intragroupe restant à subdiviser chez la mère',N'MESURE',NULL,N'MESURE justifiée par le script 106 : les 12 filiales portent chacune un compte 4551 vers la mère, qui porte un seul compte 266 global. L''article 411-3 permet la subdivision par filiale sans l''imposer. La vue compte ce qui reste à subdiviser, et le contrôle de symétrie du script 94 rapproche les 2 côtés par les montants.',N'28',NULL,NULL),
        (N'v_controle_decision_sans_visa',NULL,N'controle decision sans visa',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'29',NULL,NULL),
        (N'v_controle_demande_sans_compte_rendu',NULL,N'controle demande sans compte rendu',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'30',NULL,NULL),
        (N'v_controle_demande_sans_suite',NULL,N'controle demande sans suite',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'101',NULL,NULL),
        (N'v_controle_difference_titres',NULL,N'controle difference titres',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'31',NULL,NULL),
        (N'v_controle_difference_vs_ecritures',N'C84',N'Difference d''estimation : les actifs rapproches des ecritures de reevaluation',N'RAPPROCHEMENT',N'en_anomalie = 1',N'Reglement ANC 2021-09, articles 211-6, 212-4 et 213-4. Rapprochement pose le 09/09/2026 : aucun controle ne remontait des ecritures vers les actifs qui les fondent, et un ecart de 530 000,00 sur les immeubles du vehicule au 31/12/2025 etait reste invisible.',N'108',NULL,NULL),
        (N'v_controle_distribution_hors_bornes',NULL,N'controle distribution hors bornes',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'32',NULL,NULL),
        (N'v_controle_document_hors_cloture',NULL,N'controle document hors cloture',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'33',NULL,NULL),
        (N'v_controle_double_chemin_de_compte',N'C82',N'Natures atteintes par plusieurs comptes du plan d''une entité',N'MESURE',NULL,N'MESURE de l''état de la correspondance entre les 2 plans. Une nature atteinte par 2 comptes n''est pas une faute : elle décrit une entité dont le plan propre coexiste avec les comptes du modèle, tant que la traduction n''est pas faite. Le compteur tombera de lui-même à mesure des traductions.',N'92',NULL,NULL),
        (N'v_controle_ecart_275_inexplique',NULL,N'controle ecart 275 inexplique',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'93',NULL,NULL),
        (N'v_controle_ecart_de_reprise',NULL,N'controle ecart de reprise',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'94',NULL,NULL),
        (N'v_controle_emprunt_vs_balance',NULL,N'controle emprunt vs balance',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'34',NULL,NULL),
        (N'v_controle_entite_sans_viseur',NULL,N'controle entite sans viseur',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'35',NULL,NULL),
        (N'v_controle_exigence_manquante',N'C40',N'Pièces attendues au dossier et non encore déposées',N'MESURE',NULL,N'MESURE de l''avancement du dossier, non défaut de la base. Une exigence non satisfaite appelle une pièce du client, pas une correction du logiciel. Le compteur mesure le travail restant du cabinet.',N'36',NULL,NULL),
        (N'v_controle_expertise_sans_horodatage',NULL,N'controle expertise sans horodatage',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'37',NULL,NULL),
        (N'v_controle_expertise_sans_piece',NULL,N'controle expertise sans piece',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'38',NULL,NULL),
        (N'v_controle_filiale_plan_opci',NULL,N'controle filiale plan opci',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'39',NULL,NULL),
        (N'v_controle_filiale_reevaluee',NULL,N'controle filiale reevaluee',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'95',NULL,NULL),
        (N'v_controle_flux_vs_ecritures',NULL,N'Flux intragroupe déclarés rapprochés des écritures du débiteur',N'RAPPROCHEMENT',N'ecart_debiteur <> 0',N'Rapprochement : un flux déclaré doit se lire dans les écritures de l''entité qui le doit, au compte du modèle ; l''anomalie est l''écart non nul.',N'40',NULL,NULL),
        (N'v_controle_geste_sans_ecran',NULL,N'controle geste sans ecran',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'102',NULL,NULL),
        (N'v_controle_immeuble_non_qualifie',NULL,N'controle immeuble non qualifie',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'41',NULL,NULL),
        (N'v_controle_import_concurrent',NULL,N'controle import concurrent',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'42',NULL,NULL),
        (N'v_controle_import_exercice_faux',NULL,N'controle import exercice faux',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'43',NULL,NULL),
        (N'v_controle_import_sans_lot',NULL,N'controle import sans lot',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'44',NULL,NULL),
        (N'v_controle_inventaire_filiales',N'C67',N'Inventaire des filiales : la différence d''estimation rapprochée de sa formule',N'RAPPROCHEMENT',N'ecart_a_la_formule <> 0',N'Règlement ANC 2021-09, articles 336-2 et 212-4',N'45',NULL,NULL),
        (N'v_controle_inventaire_incomplet',NULL,N'controle inventaire incomplet',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'46',NULL,NULL),
        (N'v_controle_ligne_annexe_sans_source',NULL,N'controle ligne annexe sans source',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'47',NULL,NULL),
        (N'v_controle_lot_perime_a_trancher',N'C36',N'Lots périmés par un événement postérieur, en attente d''arbitrage',N'MESURE',NULL,N'MESURE d''une file de travail : un lot périmé attend une décision, il ne signale pas un défaut. La péremption est le mécanisme voulu.',N'48',NULL,NULL),
        (N'v_controle_lot_valide_sans_visa',NULL,N'controle lot valide sans visa',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'49',NULL,NULL),
        (N'v_controle_message_ecran_hors_bouton',NULL,N'controle message ecran hors bouton',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'103',NULL,NULL),
        (N'v_controle_miroir_impossible',NULL,N'controle miroir impossible',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'96',NULL,NULL),
        (N'v_controle_modele_sans_article',NULL,N'controle modele sans article',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'50',NULL,NULL),
        (N'v_controle_modele_sens_unique',NULL,N'controle modele sens unique',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'51',NULL,NULL),
        (N'v_controle_montant_tronque',NULL,N'controle montant tronque',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'52',NULL,NULL),
        (N'v_controle_motif_ecrase',NULL,N'controle motif ecrase',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'53',NULL,NULL),
        (N'v_controle_nature_arrete_inconnue',NULL,N'controle nature arrete inconnue',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'54',NULL,NULL),
        (N'v_controle_nature_sans_reference',NULL,N'controle nature sans reference',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'55',NULL,NULL),
        (N'v_controle_nature_sans_role',NULL,N'controle nature sans role',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'56',NULL,NULL),
        (N'v_controle_participation_non_eligible',NULL,N'controle participation non eligible',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'57',NULL,NULL),
        (N'v_controle_participation_non_qualifiee',NULL,N'controle participation non qualifiee',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'58',NULL,NULL),
        (N'v_controle_parts_courant',NULL,N'controle parts courant',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'59',NULL,NULL),
        (N'v_controle_parts_manquantes',NULL,N'controle parts manquantes',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'60',NULL,NULL),
        (N'v_controle_parts_porteurs',NULL,N'controle parts porteurs',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'61',NULL,NULL),
        (N'v_controle_permanent_hors_premier',NULL,N'controle permanent hors premier',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'62',NULL,NULL),
        (N'v_controle_piece_nature_inconnue',NULL,N'controle piece nature inconnue',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'63',NULL,NULL),
        (N'v_controle_plafond_deux_definitions',N'C70',N'Plafond de distribution : les 2 définitions rapprochées',N'RAPPROCHEMENT',N'ecart <> 0',N'CMF, article L. 214-69',N'64',NULL,NULL),
        (N'v_controle_presomption_cas_b',NULL,N'controle presomption cas b',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'65',NULL,NULL),
        (N'v_controle_publication_en_echec',NULL,N'controle publication en echec',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'106',NULL,NULL),
        (N'v_controle_question_sans_fondement',NULL,N'controle question sans fondement',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'66',NULL,NULL),
        (N'v_controle_ratio_hors_borne',N'C58',N'Ratios réglementaires hors de leur borne',N'MESURE',NULL,N'MESURE d''un constat réglementaire portant sur le DOSSIER, non sur la base. Un OPCI réellement non conforme doit être signalé, et le corriger n''appartient pas au logiciel. Les 2 écarts du jeu tiennent aux 74 620 000,00 de comptes courants intragroupe sans contrepartie comptable.',N'67',NULL,NULL),
        (N'v_controle_ratio_sans_source',NULL,N'controle ratio sans source',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'68',NULL,NULL),
        (N'v_controle_rationalisation',N'C57',N'Rationalisation de l''actif net : boucle-t-elle au seuil de 1 000,00',N'RAPPROCHEMENT',N'boucle = 0',N'Seuil arrêté par le candidat le 04/09/2026, non prescrit par le règlement',N'69',NULL,NULL),
        (N'v_controle_rattachement_incoherent',NULL,N'controle rattachement incoherent',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'70',NULL,NULL),
        (N'v_controle_rattachement_sans_entite',NULL,N'controle rattachement sans entite',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'71',NULL,NULL),
        (N'v_controle_rattachement_sans_exigence',NULL,N'controle rattachement sans exigence',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'72',NULL,NULL),
        (N'v_controle_reference_abrogee',NULL,N'controle reference abrogee',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'73',NULL,NULL),
        (N'v_controle_reference_derivee',NULL,N'controle reference derivee',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'74',NULL,NULL),
        (N'v_controle_referentiel_absent',NULL,N'controle referentiel absent',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'75',NULL,NULL),
        (N'v_controle_referentiel_sans_garde',NULL,N'controle referentiel sans garde',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'76',NULL,NULL),
        (N'v_controle_rejet_ligne_absente',NULL,N'controle rejet ligne absente',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'77',NULL,NULL),
        (N'v_controle_rejet_sans_trace',NULL,N'controle rejet sans trace',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'78',NULL,NULL),
        (N'v_controle_releve_inacheve',NULL,N'controle releve inacheve',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'79',NULL,NULL),
        (N'v_controle_reponse_forme_discordante',NULL,N'controle reponse forme discordante',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'80',NULL,NULL),
        (N'v_controle_revision_sans_ecriture',NULL,N'controle revision sans ecriture',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'81',NULL,NULL),
        (N'v_controle_role_chevauchant',NULL,N'controle role chevauchant',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'82',NULL,NULL),
        (N'v_controle_saisie_sans_motif',NULL,N'controle saisie sans motif',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'104',NULL,NULL),
        (N'v_controle_sans_date_effet',NULL,N'controle sans date effet',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'83',NULL,NULL),
        (N'v_controle_sens_contredit',NULL,N'controle sens contredit',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'97',NULL,NULL),
        (N'v_controle_sens_du_solde',N'C83',N'Sens de chaque solde des filiales, jugé au plan qu''elles appliquent',N'MESURE',NULL,N'MESURE : cette vue rend TOUS les soldes du dossier avec leur sens, soit la matière du contrôle et non son résultat. L''anomalie se lit dans v_controle_sens_contredit, qui ne retient que les soldes en contradiction avec la classe de leur compte.',N'98',NULL,NULL),
        (N'v_controle_sens_selon_le_plan',NULL,N'controle sens selon le plan',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'99',NULL,NULL),
        (N'v_controle_societe_eligible_sans_immeuble',N'C75',N'Sociétés éligibles ne détenant aucun immeuble',N'MESURE',NULL,N'MESURE posant une question au réviseur sans la trancher : la condition 2 de l''article R. 214-83 est satisfaite par vacuité, et il reste à vérifier que la société relève des 2° et 3° du I de L. 214-36.',N'84',NULL,NULL),
        (N'v_controle_solde_mal_ventile',NULL,N'controle solde mal ventile',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'100',NULL,NULL),
        (N'v_controle_symetrie_intragroupe',NULL,N'controle symetrie intragroupe',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'85',NULL,NULL),
        (N'v_controle_valeur_sans_source',NULL,N'controle valeur sans source',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'86',NULL,NULL),
        (N'v_controle_visa_de_production',NULL,N'controle visa de production',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'105',NULL,NULL),
        (N'v_controle_visa_hors_nature',NULL,N'controle visa hors nature',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'87',NULL,NULL),
        (N'v_controle_visa_lot_perime',NULL,N'controle visa lot perime',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'88',NULL,NULL),
        (N'v_controle_visa_proposant',NULL,N'controle visa proposant',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'89',NULL,NULL),
        (N'v_controle_visa_sans_role',NULL,N'controle visa sans role',N'ZERO_ATTENDU',NULL,N'inscrit automatiquement, à qualifier par l''associé',N'90',NULL,NULL);
    PRINT 'ref_controle : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'ref_controle : deja chargee, rien a faire.';
GO
