-- ref_libelle_colonne : 422 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[ref_libelle_colonne])
BEGIN
    INSERT INTO dbo.[ref_libelle_colonne] ([vue], [colonne], [libelle]) VALUES
        (N'*',N'a_saisir',N'À saisir'),
        (N'*',N'a_viser',N'À viser'),
        (N'*',N'acceptation_decision',N'Décision d''acceptation'),
        (N'*',N'acceptation_questions_dues',N'Questions dues'),
        (N'*',N'acceptation_questions_repondues',N'Questions répondues'),
        (N'*',N'acceptation_statut',N'Acceptation'),
        (N'*',N'acomptes_verses',N'Acomptes verses'),
        (N'*',N'actif_net_filiale',N'ANR de la filiale'),
        (N'*',N'actif_net_reevalue',N'ANR'),
        (N'*',N'actif_total',N'Actif total'),
        (N'*',N'actifs',N'Actifs'),
        (N'*',N'adresse',N'Adresse'),
        (N'*',N'approuve_le',N'Approuvé le'),
        (N'*',N'approuve_par',N'Approuvé par'),
        (N'*',N'arrete',N'Arrêté'),
        (N'*',N'arrete_au',N'Arrêté au'),
        (N'*',N'arrete_conclu',N'Arrêté conclu'),
        (N'*',N'arrete_couvert',N'Arrêté couvert'),
        (N'*',N'arrete_etape',N'Arrêté étape'),
        (N'*',N'arretee_le',N'Arrêtée le'),
        (N'*',N'arretee_par',N'Arrêtée par'),
        (N'*',N'arretes_ouverts',N'Arrêtés ouverts'),
        (N'*',N'article',N'Article'),
        (N'*',N'attendues',N'Attendues'),
        (N'*',N'auteur',N'Auteur'),
        (N'*',N'b0_initiale',N'Base initiale'),
        (N'*',N'balance_finale',N'Balance finale'),
        (N'*',N'balances_filiales_manquantes',N'Balances dues'),
        (N'*',N'base_calcul',N'Base de calcul'),
        (N'*',N'base_visee',N'Base visée'),
        (N'*',N'bloc',N'Bloc'),
        (N'*',N'bloques',N'Bloques'),
        (N'*',N'calcul_a_valider',N'Calcul à valider'),
        (N'*',N'calculables',N'Calculables'),
        (N'*',N'capitaux_propres',N'Capitaux propres'),
        (N'*',N'capitaux_propres_comptables',N'Capitaux propres comptables'),
        (N'*',N'cas_r214_81',N'Cas, art. R. 214-81'),
        (N'*',N'categorie',N'Catégorie'),
        (N'*',N'categories_renseignees',N'Categories renseignees'),
        (N'*',N'changements_substantiels',N'Changements substantiels'),
        (N'*',N'chef_de_mission',N'Chef de mission'),
        (N'*',N'citation',N'Citation'),
        (N'*',N'citation_courte',N'Citation, extrait'),
        (N'*',N'classe',N'Classe'),
        (N'*',N'cle_arrete',N'Clé de l''arrêté'),
        (N'*',N'cle_ecran',N'Clé'),
        (N'*',N'code',N'Code'),
        (N'*',N'code_actif',N'Actif'),
        (N'*',N'code_tiers',N'Tiers'),
        (N'*',N'collecte',N'Collecte'),
        (N'*',N'colonne',N'Colonne'),
        (N'*',N'colonne_1',N'Colonne 1'),
        (N'*',N'colonne_2',N'Colonne 2'),
        (N'*',N'colonne_3',N'Colonne 3'),
        (N'*',N'colonne_4',N'Colonne 4'),
        (N'*',N'colonne_5',N'Colonne 5'),
        (N'*',N'colonne_6',N'Colonne 6'),
        (N'*',N'commentaire',N'Commentaire'),
        (N'*',N'comp_aux_lib',N'Libellé du compte auxiliaire'),
        (N'*',N'comp_aux_num',N'Compte auxiliaire'),
        (N'*',N'compte',N'Compte'),
        (N'*',N'compte_contrepartie',N'Compte contrepartie'),
        (N'*',N'compte_crediteur',N'Compte crediteur'),
        (N'*',N'compte_debiteur',N'Compte debiteur'),
        (N'*',N'compte_entite',N'Compte de l''entité'),
        (N'*',N'compte_fichier',N'Compte fichier'),
        (N'*',N'compte_lib',N'Libellé du compte'),
        (N'*',N'compte_libelle',N'Libellé du compte'),
        (N'*',N'compte_modele',N'Compte modele'),
        (N'*',N'compte_num',N'Numéro de compte'),
        (N'*',N'compte_origine',N'Compte d’origine'),
        (N'*',N'conclue_le',N'Conclue le'),
        (N'*',N'conclue_par',N'Conclue par'),
        (N'*',N'conclusion',N'Conclusion'),
        (N'*',N'conforme',N'Conforme'),
        (N'*',N'conservation',N'Conservation'),
        (N'*',N'cote',N'Cote'),
        (N'*',N'cote_questionnaire',N'Cote du questionnaire'),
        (N'*',N'creance_vue_de_l_opci',N'Créance vue par l’OPCI'),
        (N'*',N'credit',N'Crédit'),
        (N'*',N'cree_le',N'Créé le'),
        (N'*',N'cree_par',N'Créé par'),
        (N'*',N'cycle',N'Cycle, code'),
        (N'*',N'cycle_affiche',N'Cycle affiche'),
        (N'*',N'cycle_libelle',N'Cycle'),
        (N'*',N'cycle_ordre',N'Cycle, rang'),
        (N'*',N'date_acquisition',N'Acquisition'),
        (N'*',N'date_arrete',N'Date d’arrêté'),
        (N'*',N'date_assemblee',N'Assemblée'),
        (N'*',N'date_ecriture',N'Date'),
        (N'*',N'date_etat',N'Date d’état'),
        (N'*',N'date_rapport',N'Date du rapport'),
        (N'*',N'date_valeur',N'Date de valeur'),
        (N'*',N'debit',N'Débit'),
        (N'*',N'decision',N'Décision'),
        (N'*',N'decisions',N'Decisions'),
        (N'*',N'delai_depasse',N'Delai depasse'),
        (N'*',N'demande_en_attente',N'Demande en attente'),
        (N'*',N'denominateur',N'Dénominateur'),
        (N'*',N'denomination',N'Denomination'),
        (N'*',N'depose_le',N'Déposé le'),
        (N'*',N'depose_par',N'Déposé par'),
        (N'*',N'dernier_arrete_ouvert',N'Dernier arrêté'),
        (N'*',N'dernier_decideur',N'Dernier decideur'),
        (N'*',N'dernier_message',N'Dernier message'),
        (N'*',N'dernier_saisi_le',N'Dernier saisi le'),
        (N'*',N'derniere_decision',N'Dernière décision'),
        (N'*',N'derniere_version',N'Dernière version'),
        (N'*',N'difference_estimation',N'Différence d’estimation'),
        (N'*',N'differences_d_estimation',N'Différences d’estimation'),
        (N'*',N'differences_estimation',N'Différences estimation'),
        (N'*',N'droit_r214_82',N'Droit, art. R. 214-82'),
        (N'*',N'ecart',N'Écart'),
        (N'*',N'ecart_a_moins_b',N'Écart A moins B'),
        (N'*',N'ecriture_date',N'Date'),
        (N'*',N'ecriture_let',N'Lettrage'),
        (N'*',N'ecriture_lib',N'Libellé de l''écriture'),
        (N'*',N'ecriture_num',N'N° d’écriture'),
        (N'*',N'ecritures',N'Écritures'),
        (N'*',N'en_cours',N'En cours'),
        (N'*',N'encours_vu_de_la_filiale',N'Encours vu par la filiale'),
        (N'*',N'enonce',N'Énoncé'),
        (N'*',N'enregistre_le',N'Enregistre le'),
        (N'*',N'enregistre_par',N'Enregistre par'),
        (N'*',N'entite',N'Entité'),
        (N'*',N'entite_couverte',N'Entité couverte'),
        (N'*',N'entite_debitrice',N'Entité debitrice'),
        (N'*',N'entite_detentrice',N'Entité detentrice'),
        (N'*',N'entite_fille',N'Entité fille'),
        (N'*',N'entite_libelle',N'Entité, dénomination'),
        (N'*',N'entite_liee',N'Entité liée'),
        (N'*',N'entite_mere',N'Mère'),
        (N'*',N'entree_attendue',N'Entree attendue'),
        (N'*',N'est_dernier_exercice',N'Dernier exercice'),
        (N'*',N'est_filiale',N'Est une filiale'),
        (N'*',N'etape',N'Étape, code'),
        (N'*',N'etape_5_cloturee',N'Étape 5 close'),
        (N'*',N'etape_en_cours',N'Étape en cours'),
        (N'*',N'etape_libelle',N'Étape'),
        (N'*',N'etape_ordre',N'Rang de l''étape'),
        (N'*',N'etat',N'État'),
        (N'*',N'etat_cycle',N'État cycle'),
        (N'*',N'etat_entree',N'État entree'),
        (N'*',N'etat_ligne',N'État ligne'),
        (N'*',N'etat_rattachement',N'État rattachement'),
        (N'*',N'exercice',N'Exercice'),
        (N'*',N'exercice_debut',N'Début d’exercice'),
        (N'*',N'exercice_fin',N'Fin d’exercice'),
        (N'*',N'exercice_n',N'Exercice N'),
        (N'*',N'exercice_n_1',N'Exercice N-1'),
        (N'*',N'exigence',N'Exigence'),
        (N'*',N'expert',N'Expert'),
        (N'*',N'expertise_id',N'Expertise'),
        (N'*',N'expertises_manquantes',N'Expertises dues'),
        (N'*',N'fait',N'Fait'),
        (N'*',N'famille',N'Famille, code'),
        (N'*',N'famille_libelle',N'Famille'),
        (N'*',N'famille_libelle_court',N'Famille libellé court'),
        (N'*',N'famille_ordre',N'Famille ordre'),
        (N'*',N'feuille_cote',N'Feuille cote'),
        (N'*',N'feuille_question_id',N'Question, identifiant'),
        (N'*',N'feuille_regularisation',N'Feuille regularisation'),
        (N'*',N'feuilles',N'Feuilles'),
        (N'*',N'feuilles_conclues',N'Feuilles conclues'),
        (N'*',N'filiale',N'Filiale'),
        (N'*',N'fongible',N'Fongible'),
        (N'*',N'format',N'Format'),
        (N'*',N'forme',N'Forme'),
        (N'*',N'forme_conclusion',N'Forme conclusion'),
        (N'*',N'forme_proposee',N'Forme proposee'),
        (N'*',N'forme_vehicule',N'Forme vehicule'),
        (N'*',N'genre',N'Genre'),
        (N'*',N'geste',N'Geste'),
        (N'*',N'horodatage',N'Horodatage'),
        (N'*',N'id',N'Identifiant'),
        (N'*',N'id_devise',N'Devise'),
        (N'*',N'import_id',N'Import'),
        (N'*',N'importe_le',N'Importé le'),
        (N'*',N'importe_par',N'Importé par'),
        (N'*',N'imports',N'Imports'),
        (N'*',N'imports_charges',N'Imports charges'),
        (N'*',N'imports_rejetes',N'Imports rejetes'),
        (N'*',N'indicatif',N'Indicatif'),
        (N'*',N'interets_de_la_periode',N'Intérêts de la période'),
        (N'*',N'issue',N'Issue'),
        (N'*',N'journal_code',N'Journal'),
        (N'*',N'journal_lib',N'Libellé du journal'),
        (N'*',N'libelle',N'Libellé'),
        (N'*',N'libelle_entite',N'Libellé entité'),
        (N'*',N'ligne',N'Ligne'),
        (N'*',N'lignes',N'Lignes'),
        (N'*',N'lignes_lues',N'Lignes lues'),
        (N'*',N'livrable',N'Livrable'),
        (N'*',N'livrables',N'Livrables'),
        (N'*',N'lot_famille',N'Famille du lot'),
        (N'*',N'lot_id',N'Lot'),
        (N'*',N'lot_perime',N'Lot périmé'),
        (N'*',N'lot_statut',N'Statut du lot'),
        (N'*',N'lots',N'Lots'),
        (N'*',N'lots_perimes',N'Lots périmés'),
        (N'*',N'lots_proposes',N'Lots proposés'),
        (N'*',N'lu_le',N'Lu le'),
        (N'*',N'maintien_decision',N'Décision de maintien'),
        (N'*',N'message',N'Message'),
        (N'*',N'message_ecran',N'Message de l''écran'),
        (N'*',N'methode',N'Méthode'),
        (N'*',N'modele',N'Modele'),
        (N'*',N'modifie_par',N'Modifié par'),
        (N'*',N'montant',N'Montant'),
        (N'*',N'montant_decide',N'Montant décidé'),
        (N'*',N'montant_propose',N'Montant propose'),
        (N'*',N'montant_saisi',N'Montant saisi'),
        (N'*',N'montant_vise',N'Montant visé'),
        (N'*',N'motif',N'Motif'),
        (N'*',N'motif_ecart',N'Motif écart'),
        (N'*',N'motif_le',N'Motif le'),
        (N'*',N'motif_limitation',N'Motif limitation'),
        (N'*',N'motif_non_applicable',N'Motif non applicable'),
        (N'*',N'motif_par',N'Motif par'),
        (N'*',N'motif_refus',N'Motif refus'),
        (N'*',N'motif_rejet',N'Motif rejet'),
        (N'*',N'motif_renvoi',N'Motif renvoi'),
        (N'*',N'nature',N'Nature, code'),
        (N'*',N'nature_libelle',N'Nature'),
        (N'*',N'neutralise_chez_l_opci',N'Neutralisé chez l’OPCI'),
        (N'*',N'nom_fichier',N'Fichier'),
        (N'*',N'nombre_actifs',N'Nombre actifs'),
        (N'*',N'nombre_parts',N'Nombre de parts'),
        (N'*',N'norme',N'Norme'),
        (N'*',N'note',N'Note'),
        (N'*',N'numerateur',N'Numérateur'),
        (N'*',N'numero_ligne',N'Numéro ligne'),
        (N'*',N'objet_id',N'Objet, identifiant'),
        (N'*',N'objet_ref',N'Objet, référence'),
        (N'*',N'obligation_minimale',N'Obligation minimale'),
        (N'*',N'obligatoire',N'Obligatoire'),
        (N'*',N'od_revision',N'OD de révision'),
        (N'*',N'od_valorisation',N'OD de valorisation'),
        (N'*',N'opci',N'OPCI'),
        (N'*',N'ordre',N'Ordre'),
        (N'*',N'ordre_affichage',N'Ordre affichage'),
        (N'*',N'origine',N'Origine'),
        (N'*',N'ouvert_le',N'Ouvert le'),
        (N'*',N'ouvert_par',N'Ouvert par'),
        (N'*',N'par',N'Par'),
        (N'*',N'part',N'Part'),
        (N'*',N'parts_detenues',N'Parts détenues'),
        (N'*',N'perime',N'Périmé'),
        (N'*',N'perime_le',N'Périmé le'),
        (N'*',N'perime_motif',N'Motif de péremption'),
        (N'*',N'perime_par',N'Périmé par'),
        (N'*',N'periode_debut',N'Début de période'),
        (N'*',N'periode_fin',N'Fin de période'),
        (N'*',N'periodicite',N'Périodicité'),
        (N'*',N'phase',N'Phase'),
        (N'*',N'piece_attendue_id',N'Pièce attendue'),
        (N'*',N'piece_date',N'Date de pièce'),
        (N'*',N'piece_id',N'Pièce, identifiant'),
        (N'*',N'piece_ref',N'Pièce'),
        (N'*',N'piece_synthese',N'Pièce synthese'),
        (N'*',N'pieces',N'Pièces'),
        (N'*',N'pieces_fournies',N'Pièces fournies'),
        (N'*',N'plafond_distribuable',N'Plafond distribuable'),
        (N'*',N'plafond_inferieur_obligation',N'Plafond inferieur obligation'),
        (N'*',N'plus_values_distribuables',N'Plus-values distribuables'),
        (N'*',N'porte_actif',N'Porte actif'),
        (N'*',N'porte_balance',N'Porte balance'),
        (N'*',N'porte_intragroupe',N'Porte intragroupe'),
        (N'*',N'portee',N'Portee'),
        (N'*',N'porteur_id',N'Porteur identifiant'),
        (N'*',N'poste_bilan',N'Poste du bilan'),
        (N'*',N'preparateur',N'Préparateur'),
        (N'*',N'prepare_le',N'Préparé le'),
        (N'*',N'prepare_par',N'Préparé par'),
        (N'*',N'prix_de_revient',N'Prix de revient'),
        (N'*',N'procedure_nom',N'Procédure'),
        (N'*',N'produit_le',N'Produit le'),
        (N'*',N'produit_par',N'Produit par'),
        (N'*',N'propose_le',N'Proposé le'),
        (N'*',N'propose_par',N'Proposé par'),
        (N'*',N'question',N'Question'),
        (N'*',N'question_id',N'Question identifiant'),
        (N'*',N'question_reference',N'Question reference'),
        (N'*',N'quote_part',N'Quote-part'),
        (N'*',N'rachats',N'Rachats'),
        (N'*',N'racine_declenchante',N'Racine declenchante'),
        (N'*',N'rapport_depose',N'Rapport déposé'),
        (N'*',N'rapport_gestion',N'Rapport gestion'),
        (N'*',N'ratio',N'Ratio'),
        (N'*',N'rattache_le',N'Rattache le'),
        (N'*',N'rattache_par',N'Rattache par'),
        (N'*',N'rattachement_libelle',N'Rattachement libellé'),
        (N'*',N'reciproque_par_construction',N'Reciproque par construction'),
        (N'*',N'reference',N'Référence'),
        (N'*',N'refuse_le',N'Refuse le'),
        (N'*',N'refuse_pour',N'Refuse pour'),
        (N'*',N'remplies',N'Remplies'),
        (N'*',N'renvoi',N'Renvoi'),
        (N'*',N'renvoyes',N'Renvoyes'),
        (N'*',N'repondu_le',N'Répondu le'),
        (N'*',N'repondu_par',N'Répondu par'),
        (N'*',N'reponse',N'Réponse'),
        (N'*',N'reponse_lue',N'Réponse lue'),
        (N'*',N'reponse_valeur',N'Réponse valeur'),
        (N'*',N'reprise_motif',N'Motif de reprise'),
        (N'*',N'resultat_distribuable',N'Résultat distribuable'),
        (N'*',N'revise_le',N'Révisé le'),
        (N'*',N'reviseur',N'Réviseur'),
        (N'*',N'revision',N'Révision'),
        (N'*',N'romain',N'Romain'),
        (N'*',N'saisi_le',N'Saisi le'),
        (N'*',N'saisi_par',N'Saisi par'),
        (N'*',N'secteur',N'Secteur'),
        (N'*',N'sens',N'Sens'),
        (N'*',N'seuil',N'Seuil'),
        (N'*',N'solde',N'Solde'),
        (N'*',N'source',N'Source'),
        (N'*',N'source_du_delai',N'Source du delai'),
        (N'*',N'source_du_seuil',N'Source du seuil'),
        (N'*',N'source_valeur',N'Source valeur'),
        (N'*',N'souscriptions',N'Souscriptions'),
        (N'*',N'statut',N'Statut'),
        (N'*',N'statut_le',N'Statut, le'),
        (N'*',N'statut_par',N'Statut, par'),
        (N'*',N'supprimable',N'Supprimable'),
        (N'*',N'surface_m2',N'Surface, m²'),
        (N'*',N'tableau',N'Tableau'),
        (N'*',N'taux',N'Taux'),
        (N'*',N'total',N'Total'),
        (N'*',N'total_distribuable',N'Total distribuable'),
        (N'*',N'type_arrete',N'Type d’arrêté'),
        (N'*',N'type_ligne',N'Type de ligne'),
        (N'*',N'unite',N'Unité, code'),
        (N'*',N'unite_libelle',N'Unité'),
        (N'*',N'usages',N'Usages'),
        (N'*',N'usages_qualifies',N'Usages qualifiés'),
        (N'*',N'valeur',N'Valeur'),
        (N'*',N'valeur_actuelle',N'Valeur actuelle'),
        (N'*',N'valeur_comptable',N'Valeur comptable'),
        (N'*',N'valeur_liquidative',N'Valeur liquidative'),
        (N'*',N'valeur_liquidative_precedente',N'Valeur liquidative precedente'),
        (N'*',N'valeur_retenue',N'Valeur retenue'),
        (N'*',N'valeur_titres_a_la_quote_part',N'Valeur titres à la quote part'),
        (N'*',N'valid_date',N'Validation'),
        (N'*',N'valorisation',N'Valorisation'),
        (N'*',N'variation_calculable',N'Variation calculable'),
        (N'*',N'vehicule',N'Vehicule'),
        (N'*',N'version',N'Version'),
        (N'*',N'version_regles',N'Version des règles'),
        (N'*',N'vise_le',N'Visé le'),
        (N'*',N'vise_par',N'Visé par'),
        (N'*',N'vises',N'Vises'),
        (N'*',N'xref',N'Référence croisée'),
        (N'v_ctx_avancement_1ligne',N'arrete_etape',N'Arrêté'),
        (N'v_ctx_avancement_1ligne',N'collecte',N'Collecte'),
        (N'v_ctx_avancement_1ligne',N'etape_en_cours',N'Étape en cours'),
        (N'v_ctx_avancement_1ligne',N'livrables',N'Livrables'),
        (N'v_ctx_avancement_1ligne',N'revision',N'Révision'),
        (N'v_ctx_avancement_1ligne',N'valorisation',N'Valorisation'),
        (N'v_ecran_actifs_expertise_requise',N'citation_courte',N'Citation'),
        (N'v_ecran_actifs_expertise_requise',N'fondement_evaluateur',N'Fondement'),
        (N'v_ecran_actifs_expertise_requise',N'rapport_au_coffre',N'Au coffre'),
        (N'v_ecran_actifs_expertise_requise',N'valeur_externe_attendue',N'Valeur externe'),
        (N'v_ecran_actifs_expertise_requise',N'valeur_retenue_saisie',N'Valeur retenue'),
        (N'v_ecran_c11_dossiers',N'acceptation_decision',N'Décision'),
        (N'v_ecran_c11_dossiers',N'acceptation_questions_dues',N'Questions dues'),
        (N'v_ecran_c11_dossiers',N'acceptation_questions_repondues',N'Questions répondues'),
        (N'v_ecran_c11_dossiers',N'acceptation_statut',N'Acceptation'),
        (N'v_ecran_c11_dossiers',N'arretes_ouverts',N'Arrêtés ouverts'),
        (N'v_ecran_c11_dossiers',N'balances_filiales_manquantes',N'Balances dues'),
        (N'v_ecran_c11_dossiers',N'chef_de_mission',N'Chef de mission'),
        (N'v_ecran_c11_dossiers',N'dernier_arrete_ouvert',N'Dernier arrêté'),
        (N'v_ecran_c11_dossiers',N'entite_libelle',N'Entité'),
        (N'v_ecran_c11_dossiers',N'expertises_manquantes',N'Expertises dues'),
        (N'v_ecran_c11_dossiers',N'feuilles_conclues',N'Feuilles conclues'),
        (N'v_ecran_c11_dossiers',N'maintien_decision',N'Décision de maintien'),
        (N'v_ecran_c11_dossiers',N'maintien_statut',N'Maintien'),
        (N'v_ecran_c11_questions',N'motif_non_applicable',N'Sans objet, motif'),
        (N'v_ecran_c11_questions',N'repondu_le',N'Le'),
        (N'v_ecran_c11_questions',N'repondu_par',N'Répondu par'),
        (N'v_ecran_c11_questions',N'reponse_valeur',N'Valeur'),
        (N'v_ecran_carnet_import',N'ecritures_produites',N'Écritures produites'),
        (N'v_ecran_carnet_import',N'exercice_conforme',N'Exercice conforme'),
        (N'v_ecran_carnet_import',N'lignes_rejetees',N'Lignes rejetées'),
        (N'v_ecran_carnet_import',N'motif_non_conforme',N'Motif'),
        (N'v_ecran_carnet_import',N'refus_du_fichier',N'Refus'),
        (N'v_ecran_carnet_import',N'rejets_conserves',N'Rejets conservés'),
        (N'v_ecran_etat_rapport_annuel',N'certification_cac',N'Certification'),
        (N'v_ecran_etat_rapport_annuel',N'documents_synthese',N'Documents'),
        (N'v_ecran_etat_rapport_annuel',N'echeance_75_jours',N'Échéance'),
        (N'v_ecran_etat_rapport_annuel',N'piece_certification',N'Pièce'),
        (N'v_ecran_etat_rapport_annuel',N'rapport_conseil_fpi',N'Rapport du conseil'),
        (N'v_ecran_flux_intragroupe',N'creditrice_libelle',N'Créditrice, nom'),
        (N'v_ecran_flux_intragroupe',N'debitrice_libelle',N'Débitrice, nom'),
        (N'v_ecran_flux_intragroupe',N'entite_creditrice',N'Créditrice'),
        (N'v_ecran_obligation_par_categorie',N'total_distribuable',N'Distribuable'),
        (N'v_ecran_perimetre_arrete',N'etat_rattachement',N'Rattachement'),
        (N'v_ecran_piece_du_coffre',N'expertises_fondees',N'Expertises'),
        (N'v_ecran_rationalisation_filiale',N'interets_reintegres',N'Intérêts réintégrés'),
        (N'v_ecran_rationalisation_filiale',N'neutralise_chez_l_opci',N'Neutralisé'),
        (N'v_ecran_rationalisation_filiale',N'variation_calculee_b',N'Variation calculée'),
        (N'v_ecran_rationalisation_filiale',N'variation_rationalisee_a',N'Variation rationalisée'),
        (N'v_ecran_rationalisation_opci',N'actif_net_calcule',N'ANR calculé'),
        (N'v_ecran_rationalisation_opci',N'actif_net_precedent',N'ANR précédent'),
        (N'v_ecran_rationalisation_opci',N'actif_net_rationalise',N'ANR rationalisé'),
        (N'v_ecran_rationalisation_opci',N'arrete_precedent',N'Arrêté précédent'),
        (N'v_ecran_rationalisation_opci',N'dividendes_internes_pour_memoire',N'Dividendes internes'),
        (N'v_ecran_rationalisation_opci',N'dividendes_verses',N'Dividendes versés'),
        (N'v_ecran_rationalisation_opci',N'gain_valorisations',N'Gains de valorisation'),
        (N'v_ecran_rationalisation_opci',N'interets_internes_elimines',N'Intérêts éliminés'),
        (N'v_ecran_rationalisation_opci',N'plus_values_cession',N'Plus-values'),
        (N'v_ecran_rationalisation_opci',N'resultat_corporate',N'Résultat corporate'),
        (N'v_ecran_rationalisation_opci',N'resultat_financier',N'Résultat financier'),
        (N'v_ecran_rationalisation_opci',N'resultat_immobilier',N'Résultat immobilier'),
        (N'v_ecran_titres_valeur_actuelle',N'actif_net_filiale',N'ANR de la filiale'),
        (N'v_ecran_titres_valeur_actuelle',N'compte_difference_estimation',N'Compte de différence'),
        (N'v_ecran_titres_valeur_actuelle',N'difference_estimation_titres',N'Différence'),
        (N'v_ecran_titres_valeur_actuelle',N'valeur_actuelle_titres',N'Valeur actuelle'),
        (N'v_ecran_titres_valeur_actuelle',N'valeur_comptable_compte_courant',N'Compte courant'),
        (N'v_ecran_titres_valeur_actuelle',N'valeur_comptable_titres',N'Valeur comptable'),
        (N'v_ecran_titres_valeur_actuelle',N'valeur_de_detention',N'Détention'),
        (N'v_ecran_titres_valeur_actuelle',N'valeur_titres_a_la_quote_part',N'Quote-part');
    PRINT 'ref_libelle_colonne : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'ref_libelle_colonne : deja chargee, rien a faire.';
GO
