-- ref_ligne_etat : 84 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[ref_ligne_etat])
BEGIN
    INSERT INTO dbo.[ref_ligne_etat] ([etat], [code], [libelle], [type_ligne], [romain], [racines], [sens], [formule], [renvoi], [article], [ordre], [modifie_par], [modifie_le]) VALUES
        (N'BILAN_ACTIF',N'A_AUTRE',N'Autres actifs',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'321-2',N'18',NULL,NULL),
        (N'BILAN_ACTIF',N'A_AUTRE_1',N'Créances locataires',N'DETAIL',NULL,N'42,491',N'DEBIT',NULL,NULL,N'321-2',N'19',NULL,NULL),
        (N'BILAN_ACTIF',N'A_AUTRE_2',N'Autres créances',N'DETAIL',NULL,N'41,44,45,46,47,48,496',N'DEBIT',NULL,NULL,N'321-2',N'20',NULL,NULL),
        (N'BILAN_ACTIF',N'A_AUTRE_3',N'Dépôts à vue',N'DETAIL',NULL,N'511,57,58',N'DEBIT',NULL,NULL,N'321-2',N'21',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN',N'Dépôts et instruments financiers non immobiliers',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'321-2',N'10',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN_1',N'Actions et valeurs assimilées',N'DETAIL',NULL,N'30',N'DEBIT',NULL,NULL,N'321-2',N'11',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN_2',N'Obligations et valeurs assimilées',N'DETAIL',NULL,N'31',N'DEBIT',NULL,NULL,N'321-2',N'12',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN_3',N'Titres de créances',N'DETAIL',NULL,N'32',N'DEBIT',NULL,NULL,N'321-2',N'13',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN_4',N'Organismes de placement collectif à capital variable (OPCVM et FIA)',N'DETAIL',NULL,N'33,34',N'DEBIT',NULL,NULL,N'321-2',N'14',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN_5',N'Dépôts',N'DETAIL',NULL,N'35',N'DEBIT',NULL,NULL,N'321-2',N'15',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN_6',N'Opérations temporaires sur titres',N'DETAIL',NULL,N'36',N'DEBIT',NULL,NULL,N'321-2',N'16',NULL,NULL),
        (N'BILAN_ACTIF',N'A_FIN_7',N'Instruments financiers à terme',N'DETAIL',NULL,N'37,38',N'DEBIT',NULL,NULL,N'321-2',N'17',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO',N'Actifs à caractère immobilier',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'321-2',N'1',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_1',N'Immeubles en cours, construits ou acquis et droits réels',N'DETAIL',NULL,N'21,22,23,271,272,273',N'DEBIT',NULL,NULL,N'321-2',N'2',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_2',N'Contrats de crédit-bail',N'DETAIL',NULL,N'243,274',N'DEBIT',NULL,NULL,N'321-2',N'3',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_3',N'Parts des sociétés de personnes article L214-36 2ème alinéa',N'DETAIL',NULL,N'252',N'DEBIT',NULL,NULL,N'321-2',N'4',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_4',N'Parts et actions des sociétés article L214-36 3ème alinéa',N'DETAIL',NULL,N'254',N'DEBIT',NULL,NULL,N'321-2',N'5',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_5',N'Actions négociées sur un marché réglementé article L214-36 4ème alinéa',N'DETAIL',NULL,N'256',N'DEBIT',NULL,NULL,N'321-2',N'6',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_6',N'OPCI et organismes étrangers équivalents article L214-36 5ème alinéa',N'DETAIL',NULL,N'258',N'DEBIT',NULL,NULL,N'321-2',N'7',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_7',N'Avances preneurs sur crédit-bail',N'DETAIL',NULL,N'245',N'DEBIT',NULL,NULL,N'321-2',N'8',NULL,NULL),
        (N'BILAN_ACTIF',N'A_IMMO_8',N'Autres actifs à caractère immobilier (1)',N'DETAIL',NULL,N'265,266,275,276',N'DEBIT',NULL,N'Renvoi (1) de l''article 321-2 : les autres actifs a caractere immobilier comprennent les avances en compte courant et les depots et cautionnements verses.',N'321-2',N'9',NULL,NULL),
        (N'BILAN_ACTIF',N'A_TOTAL',N'Total de l''actif',N'TOTAL',NULL,NULL,NULL,N'somme des lignes de detail',NULL,N'321-2',N'22',NULL,NULL),
        (N'BILAN_PASSIF',N'P_CP',N'Capitaux propres (= actif net)',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'321-6',N'1',NULL,NULL),
        (N'BILAN_PASSIF',N'P_CP_1',N'Capital',N'DETAIL',NULL,N'101,102,103,104,105,106,107,108,109',N'CREDIT',NULL,N'Article 321-3 : le capital est compose des souscriptions nettes des rachats, des commissions acquises, des frais de constitution, des differences d''estimation, des ecarts de change latents, des frais d''acquisition, des resultats anterieurs incorpores et des autres elements de capital.',N'321-6',N'2',NULL,NULL),
        (N'BILAN_PASSIF',N'P_CP_2',N'Report des plus-values nettes réalisées (1)',N'DETAIL',NULL,N'112,193',N'CREDIT',NULL,N'Renvoi (1) de l''article 321-6 : y compris comptes de regularisation.',N'321-6',N'3',NULL,NULL),
        (N'BILAN_PASSIF',N'P_CP_3',N'Report des résultats nets antérieurs (1)',N'DETAIL',NULL,N'111,191',N'CREDIT',NULL,N'Renvoi (1) de l''article 321-6 : y compris comptes de regularisation.',N'321-6',N'4',NULL,NULL),
        (N'BILAN_PASSIF',N'P_CP_4',N'Résultat de l''exercice (1)',N'DETAIL',NULL,N'120,192',N'CREDIT',NULL,N'Renvoi (1) de l''article 321-6 : y compris comptes de regularisation.',N'321-6',N'5',NULL,NULL),
        (N'BILAN_PASSIF',N'P_CP_5',N'Acomptes versés au cours de l''exercice (1)',N'DETAIL',NULL,N'129,198',N'CREDIT',NULL,N'Renvoi (1) de l''article 321-6 : y compris comptes de regularisation. Article 321-5 : les acomptes verses au titre de l''exercice sont comptabilises dans un compte de capitaux propres.',N'321-6',N'6',NULL,NULL),
        (N'BILAN_PASSIF',N'P_DET',N'Dettes',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'321-6',N'17',NULL,NULL),
        (N'BILAN_PASSIF',N'P_DET_1',N'Emprunts envers les établissements de crédit',N'DETAIL',NULL,N'164,512,518',N'CREDIT',NULL,NULL,N'321-6',N'18',NULL,NULL),
        (N'BILAN_PASSIF',N'P_DET_2',N'Autres emprunts et dettes financières',N'DETAIL',NULL,N'513',N'CREDIT',NULL,NULL,N'321-6',N'19',NULL,NULL),
        (N'BILAN_PASSIF',N'P_DET_3',N'Concours bancaires courants',N'DETAIL',NULL,N'519',N'CREDIT',NULL,N'Le compte 511 du plan de l''article 411-3 porte les comptes a vue, liquidites ET concours bancaires courants : un solde crediteur du 511 se lit ici.',N'321-6',N'20',NULL,NULL),
        (N'BILAN_PASSIF',N'P_DET_4',N'Dépôts de garantie reçus',N'DETAIL',NULL,N'43',N'CREDIT',NULL,NULL,N'321-6',N'21',NULL,NULL),
        (N'BILAN_PASSIF',N'P_DET_5',N'Autres dettes d''exploitation',N'DETAIL',NULL,N'402,403,404,405,408,409,44,45,46,47,48',N'CREDIT',NULL,NULL,N'321-6',N'22',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IF',N'Instruments financiers',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'321-6',N'13',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IF_1',N'Opérations de cessions sur instruments financiers',N'DETAIL',NULL,N'39',N'CREDIT',NULL,NULL,N'321-6',N'14',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IF_2',N'Opérations temporaires sur titres',N'DETAIL',NULL,N'406',N'CREDIT',NULL,NULL,N'321-6',N'15',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IF_3',N'Instruments financiers à terme',N'DETAIL',NULL,N'401,411',N'CREDIT',NULL,NULL,N'321-6',N'16',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IMMO',N'Passifs liés aux actifs à caractère immobilier',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'321-6',N'8',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IMMO_1',N'Dettes sur rentes viagères',N'DETAIL',NULL,N'291',N'CREDIT',NULL,NULL,N'321-6',N'9',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IMMO_2',N'Provisions sur droits nés de contrats de crédit-bail',N'DETAIL',NULL,N'294',N'CREDIT',NULL,NULL,N'321-6',N'10',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IMMO_3',N'Provisions sur filiales et participations',N'DETAIL',NULL,N'295',N'CREDIT',NULL,NULL,N'321-6',N'11',NULL,NULL),
        (N'BILAN_PASSIF',N'P_IMMO_4',N'Autres passifs liés aux actifs à caractère immobilier',N'DETAIL',NULL,N'296',N'CREDIT',NULL,NULL,N'321-6',N'12',NULL,NULL),
        (N'BILAN_PASSIF',N'P_PROV',N'Provisions pour risques et charges',N'DETAIL',NULL,N'497',N'CREDIT',NULL,NULL,N'321-6',N'7',NULL,NULL),
        (N'BILAN_PASSIF',N'P_TOTAL',N'Total du passif',N'TOTAL',NULL,NULL,NULL,N'somme des lignes de detail',NULL,N'321-6',N'23',NULL,NULL),
        (N'RESULTAT',N'R_CF',N'Charges sur opérations financières',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'322-2',N'17',NULL,NULL),
        (N'RESULTAT',N'R_CF_1',N'Charges sur dépôts et instruments financiers non immobiliers',N'DETAIL',NULL,N'604,605',N'DEBIT',NULL,NULL,N'322-2',N'18',NULL,NULL),
        (N'RESULTAT',N'R_CF_2',N'Autres charges financières',N'DETAIL',NULL,N'608',N'DEBIT',NULL,NULL,N'322-2',N'19',NULL,NULL),
        (N'RESULTAT',N'R_CI',N'Charges de l''activité immobilière',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'322-2',N'6',NULL,NULL),
        (N'RESULTAT',N'R_CI_1',N'Charges immobilières',N'DETAIL',NULL,N'621,622,624,625,626,627,628,629',N'DEBIT',NULL,NULL,N'322-2',N'7',NULL,NULL),
        (N'RESULTAT',N'R_CI_2',N'Charges sur parts et actions des entités à caractère immobilier',N'DETAIL',NULL,N'63',N'DEBIT',NULL,NULL,N'322-2',N'8',NULL,NULL),
        (N'RESULTAT',N'R_CI_3',N'Autres charges sur actifs à caractère immobilier',N'DETAIL',NULL,N'681',N'DEBIT',NULL,NULL,N'322-2',N'9',NULL,NULL),
        (N'RESULTAT',N'R_CI_4',N'Charges d''emprunt sur les actifs à caractère immobilier',N'DETAIL',NULL,N'623',N'DEBIT',NULL,N'Article 322-5 : les charges d''emprunt liees a des actifs immobiliers entrent dans les charges de l''activite immobiliere.',N'322-2',N'10',NULL,NULL),
        (N'RESULTAT',N'R_MV',N'Moins-values réalisées nettes',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'322-2',N'32',NULL,NULL),
        (N'RESULTAT',N'R_MV_1',N'Moins-values réalisées nettes de frais sur actifs à caractère immobilier',N'DETAIL',NULL,N'661',N'DEBIT',NULL,NULL,N'322-2',N'33',NULL,NULL),
        (N'RESULTAT',N'R_MV_2',N'Moins-values réalisées nettes de frais sur dépôts et instruments financiers non immobiliers',N'DETAIL',NULL,N'662',N'DEBIT',NULL,NULL,N'322-2',N'34',NULL,NULL),
        (N'RESULTAT',N'R_PF',N'Produits sur opérations financières',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'322-2',N'13',NULL,NULL),
        (N'RESULTAT',N'R_PF_1',N'Produits sur dépôts et instruments financiers non immobiliers',N'DETAIL',NULL,N'700,701,702,703,704,705,706',N'CREDIT',NULL,NULL,N'322-2',N'14',NULL,NULL),
        (N'RESULTAT',N'R_PF_2',N'Autres produits financiers',N'DETAIL',NULL,N'708',N'CREDIT',NULL,NULL,N'322-2',N'15',NULL,NULL),
        (N'RESULTAT',N'R_PI',N'Produits de l''activité immobilière',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'322-2',N'1',NULL,NULL),
        (N'RESULTAT',N'R_PI_1',N'Produits immobiliers',N'DETAIL',NULL,N'721,722,723,728',N'CREDIT',NULL,NULL,N'322-2',N'2',NULL,NULL),
        (N'RESULTAT',N'R_PI_2',N'Produits sur parts et actions des entités à caractère immobilier',N'DETAIL',NULL,N'73',N'CREDIT',NULL,NULL,N'322-2',N'3',NULL,NULL),
        (N'RESULTAT',N'R_PI_3',N'Autres produits sur actifs à caractère immobilier',N'DETAIL',NULL,N'724,78',N'CREDIT',NULL,N'Article 322-4 : les produits sur autres actifs immobiliers comprennent les interets des avances en compte courant.',N'322-2',N'4',NULL,NULL),
        (N'RESULTAT',N'R_PMVAR',N'Plus et moins-values réalisées nettes après régularisations (B +/- XI)',N'RESULTAT',NULL,NULL,NULL,N'R_RPMV + R_TXI',NULL,N'322-2',N'38',NULL,NULL),
        (N'RESULTAT',N'R_PV',N'Plus-values réalisées nettes',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'322-2',N'28',NULL,NULL),
        (N'RESULTAT',N'R_PV_1',N'Plus-values réalisées nettes de frais sur actifs à caractère immobilier',N'DETAIL',NULL,N'761',N'CREDIT',NULL,N'Article 211-14 : la plus ou moins-value de cession est enregistree nette des frais encourus tant a l''acquisition qu''a la cession.',N'322-2',N'29',NULL,NULL),
        (N'RESULTAT',N'R_PV_2',N'Plus-values réalisées nettes de frais sur dépôts et instruments financiers non immobiliers',N'DETAIL',NULL,N'762',N'CREDIT',NULL,NULL,N'322-2',N'30',NULL,NULL),
        (N'RESULTAT',N'R_RAI',N'Résultat de l''activité immobilière (I - II)',N'RESULTAT',NULL,NULL,NULL,N'R_TI - R_TII',N'Article 322-3 : le resultat de l''activite immobiliere ne comprend PAS les frais de gestion et de fonctionnement supportes par l''OPCI pour la gestion de ces actifs.',N'322-2',N'12',NULL,NULL),
        (N'RESULTAT',N'R_RE',N'Résultat de l''exercice (C = A +/- VIII + B +/- XI)',N'RESULTAT',N'C',NULL,NULL,N'R_RNAR + R_PMVAR',NULL,N'322-2',N'39',NULL,NULL),
        (N'RESULTAT',N'R_RN',N'Résultat net (A = I - II + III - IV + V - VI - VII)',N'RESULTAT',N'A',NULL,NULL,N'R_TI - R_TII + R_TIII - R_TIV + R_TV - R_TVI - R_TVII',N'Article 322-1 et article L. 214-51 du CMF pour la definition du resultat net.',N'322-2',N'25',NULL,NULL),
        (N'RESULTAT',N'R_RNAR',N'Résultat net après régularisations (A +/- VIII)',N'RESULTAT',NULL,NULL,NULL,N'R_RN + R_TVIII',NULL,N'322-2',N'27',NULL,NULL),
        (N'RESULTAT',N'R_ROF',N'Résultat sur opérations financières (III - IV)',N'RESULTAT',NULL,NULL,NULL,N'R_TIII - R_TIV',NULL,N'322-2',N'21',NULL,NULL),
        (N'RESULTAT',N'R_RPMV',N'Résultat des Plus et moins-values réalisées nettes (B = IX-X)',N'RESULTAT',N'B',NULL,NULL,N'R_TIX - R_TX',NULL,N'322-2',N'36',NULL,NULL),
        (N'RESULTAT',N'R_TI',N'Total I',N'TOTAL',N'I',NULL,NULL,N'R_PI_1 + R_PI_2 + R_PI_3',NULL,N'322-2',N'5',NULL,NULL),
        (N'RESULTAT',N'R_TII',N'Total II',N'TOTAL',N'II',NULL,NULL,N'R_CI_1 + R_CI_2 + R_CI_3 + R_CI_4',NULL,N'322-2',N'11',NULL,NULL),
        (N'RESULTAT',N'R_TIII',N'Total III',N'TOTAL',N'III',NULL,NULL,N'R_PF_1 + R_PF_2',NULL,N'322-2',N'16',NULL,NULL),
        (N'RESULTAT',N'R_TIV',N'Total IV',N'TOTAL',N'IV',NULL,NULL,N'R_CF_1 + R_CF_2',NULL,N'322-2',N'20',NULL,NULL),
        (N'RESULTAT',N'R_TIX',N'Total IX',N'TOTAL',N'IX',NULL,NULL,N'R_PV_1 + R_PV_2',NULL,N'322-2',N'31',NULL,NULL),
        (N'RESULTAT',N'R_TV',N'Autres produits (V)',N'DETAIL',N'V',N'71',N'CREDIT',NULL,NULL,N'322-2',N'22',NULL,NULL),
        (N'RESULTAT',N'R_TVI',N'Frais de gestion et de fonctionnement externes (VI)',N'DETAIL',N'VI',N'611,612,615,617,619',N'DEBIT',NULL,N'Article 322-10 pour les frais de gestion. Ce sont les charges corporate de l''OPCI : expert-comptable, commissaire aux comptes, depositaire, frais bancaires, domiciliation, personnel.',N'322-2',N'23',NULL,NULL),
        (N'RESULTAT',N'R_TVII',N'Autres charges (VII)',N'DETAIL',N'VII',N'613,618',N'DEBIT',NULL,NULL,N'322-2',N'24',NULL,NULL),
        (N'RESULTAT',N'R_TVIII',N'Régularisations sur résultat net (VIII)',N'DETAIL',N'VIII',N'772',N'CREDIT',NULL,N'Article 113-3 : un mecanisme correcteur neutralise l''incidence des souscriptions et des rachats sur le montant unitaire.',N'322-2',N'26',NULL,NULL),
        (N'RESULTAT',N'R_TX',N'Total X',N'TOTAL',N'X',NULL,NULL,N'R_MV_1 + R_MV_2',NULL,N'322-2',N'35',NULL,NULL),
        (N'RESULTAT',N'R_TXI',N'Régularisations sur plus et moins-values réalisées nettes (XI)',N'DETAIL',N'XI',N'776',N'CREDIT',NULL,NULL,N'322-2',N'37',NULL,NULL);
    PRINT 'ref_ligne_etat : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'ref_ligne_etat : deja chargee, rien a faire.';
GO
