-- ref_norme : 23 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[ref_norme])
BEGIN
    INSERT INTO dbo.[ref_norme] ([code], [libelle_court], [libelle_complet], [autorite], [acte_agrement], [date_application], [edition], [piece_au_dossier], [en_vigueur], [abroge_par], [applicable_presentation], [note], [modifie_par], [modifie_le]) VALUES
        (N'ANC2014-01',N'Reglement ANC 2014-01',N'Reglement ANC n° 2014-01 relatif aux comptes annuels des organismes de placement collectif a capital variable',N'ANC',NULL,NULL,NULL,NULL,N'0',N'ANC2020-07',N'0',N'ABROGE et remplace par le reglement ANC 2020-07 a compter des exercices ouverts le 1er octobre 2023.',NULL,NULL),
        (N'ANC2014-06',N'Reglement ANC 2014-06',N'Reglement ANC n° 2014-06 du 2 octobre 2014 relatif aux comptes annuels des organismes de placement collectif immobilier',N'ANC',NULL,NULL,NULL,NULL,N'0',N'ANC2021-09',N'0',N'ABROGE. La version precedente du memoire le citait massivement : ne jamais le citer.',NULL,NULL),
        (N'ANC2016-06',N'Reglement ANC 2016-06',N'Reglement ANC n° 2016-06 du 14 octobre 2016 modifiant le reglement ANC n° 2014-06',N'ANC',NULL,NULL,NULL,NULL,N'0',N'ANC2021-09',N'0',N'ABROGE avec le reglement qu''il modifiait.',NULL,NULL),
        (N'ANC2020-07',N'Reglement ANC 2020-07',N'Reglement ANC n° 2020-07 du 4 decembre 2020 relatif aux comptes annuels des organismes de placement collectif a capital variable',N'ANC',NULL,N'Exercices ouverts a compter du 1er octobre 2023, en application prospective',N'Recueil du 6 janvier 2026',N'10_MATIERE_V1/RECUEIL_GESTION-ACTIFS-2026.pdf, LIVRE I, TOME 1, pages 8 a 77',N'1',NULL,N'1',N'Modifie par le reglement ANC 2022-03. Abroge et remplace le reglement ANC 2014-01. Les OPCI l''appliquent par renvoi des articles 113-1 et 113-2 du reglement ANC 2021-09.',NULL,NULL),
        (N'ANC2021-09',N'Reglement ANC 2021-09',N'Reglement ANC n° 2021-09 du 5 novembre 2021 relatif aux comptes annuels des organismes de placement collectif immobilier',N'ANC',NULL,N'Exercices ouverts a compter du 1er octobre 2023, en application prospective',N'Recueil du 6 janvier 2026',N'10_MATIERE_V1/RECUEIL_GESTION-ACTIFS-2026.pdf, TOME 2, pages 78 a 119',N'1',NULL,N'1',N'Modifie par le reglement ANC 2024-01. Abroge et remplace les reglements ANC 2014-06 et 2016-06.',NULL,NULL),
        (N'ANC2022-03',N'Reglement ANC 2022-03',N'Reglement ANC n° 2022-03 du 3 juin 2022 relatif aux comptes annuels des organismes de placement collectif a capital variable',N'ANC',NULL,NULL,N'Recueil du 6 janvier 2026',N'10_MATIERE_V1/RECUEIL_GESTION-ACTIFS-2026.pdf, page 8',N'1',NULL,N'1',N'Modifie le reglement ANC 2020-07. Releve sur piece le 04/09/2026, page 8 du recueil.',NULL,NULL),
        (N'ANC2024-01',N'Reglement ANC 2024-01',N'Reglement ANC n° 2024-01 du 5 avril 2024 modifiant le reglement ANC n° 2021-09',N'ANC',NULL,NULL,N'Recueil du 6 janvier 2026',N'10_MATIERE_V1/RECUEIL_GESTION-ACTIFS-2026.pdf',N'1',NULL,N'1',N'Le reglement applicable aux OPCI s''ecrit toujours « reglement ANC n° 2021-09, modifie par le reglement ANC n° 2024-01 ».',NULL,NULL),
        (N'CADRE-REF',N'Cadre de reference',N'Cadre de reference des missions de l''expert-comptable',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'1',N'Page 13 du referentiel. Intitule releve au sommaire, texte non lu.',NULL,NULL),
        (N'CMF',N'Code monetaire et financier',N'Code monetaire et financier',N'LEGISLATEUR',N'Partie legislative et partie reglementaire. Les articles cites ici sont dans leur version en vigueur a la date de lecture, portee par chaque reference.',NULL,NULL,N'Legifrance, consulte les 04 et 05/09/2026',N'1',NULL,N'1',N'PAS au dossier. Ses articles sont ancres par leur numero, sans citation : le recueil en reproduit quelques-uns, jamais le code entier.',NULL,NULL),
        (N'DEONTO',N'Code de deontologie',N'Code de deontologie des professionnels de l''expertise comptable',N'LEGISLATEUR',N'Non porte par la piece au dossier. L''article 150 y est signale comme modifie par le decret n° 2022-1732 du 30 decembre 2022',N'En vigueur a la date de l''edition',N'Janvier 2024',N'15_DOCUMENTATION/code_deontologie_012024.pdf',N'1',NULL,N'1',N'15 pages, 4 sections. Les articles cites par les questionnaires vont de 141 a 163.',NULL,NULL),
        (N'NP-AUDIT',N'NP audit',N'Norme professionnelle applicable a la mission d''audit d''etats financiers',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 262 du referentiel. Ne s''applique pas a la mission de presentation.',NULL,NULL),
        (N'NP-COMM',N'NP activites commerciales',N'Norme professionnelle relative aux activites commerciales et aux actes d''intermediaire',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 265 du referentiel. Norme specifique aux activites.',NULL,NULL),
        (N'NP2300',N'NP 2300',N'Norme professionnelle applicable a la mission de presentation des comptes',N'CNOEC',N'Arrete ministeriel du 1er septembre 2016, qui annule et remplace l''agrement du 20 juin 2011',N'Exercices clos a compter du 31 decembre 2016',N'2024',N'15_DOCUMENTATION/np2300-2025.pdf',N'1',NULL,N'1',N'18 pages, page 88 du referentiel. Le fichier se nomme np2300-2025 mais son en-tete porte « Edition 2024 ».',NULL,NULL),
        (N'NP2400',N'NP 2400',N'Norme professionnelle applicable a la mission d''examen limite des comptes',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 106 du referentiel. Ne s''applique pas a la mission de presentation.',NULL,NULL),
        (N'NP2910',N'NP 2910',N'Norme professionnelle applicable a la mission d''audit d''etats financiers dans une petite entite',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 128 du referentiel. Ne s''applique pas a la mission de presentation.',NULL,NULL),
        (N'NP3100',N'NP 3100',N'Norme professionnelle applicable aux missions d''assurance sur des informations autres que des comptes complets historiques, attestations particulieres',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 180 du referentiel. Ne s''applique pas a la mission de presentation.',NULL,NULL),
        (N'NP3400',N'NP 3400',N'Norme professionnelle applicable a la mission d''examen d''informations financieres previsionnelles',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 214 du referentiel. Ne s''applique pas a la mission de presentation.',NULL,NULL),
        (N'NP4400',N'NP 4400',N'Norme professionnelle applicable a la mission d''examen d''informations sur la base de procedures convenues',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 234 du referentiel. Ne s''applique pas a la mission de presentation.',NULL,NULL),
        (N'NP4410',N'NP 4410',N'Norme professionnelle applicable a la mission de compilation des comptes',N'CNOEC',NULL,NULL,N'2025',NULL,N'1',NULL,N'0',N'Page 248 du referentiel. Ne s''applique pas a la mission de presentation.',NULL,NULL),
        (N'NPLAB',N'NPLAB',N'Norme professionnelle relative aux obligations de la profession d''expertise comptable en matiere de lutte contre le blanchiment des capitaux et le financement du terrorisme',N'CNOEC',N'Arrete ministeriel du 7 decembre 2020, JO du 13, qui annule et remplace l''agrement du 17 juillet 2019',N'A compter du 14 decembre 2020',N'2025',N'15_DOCUMENTATION/nplab-2025.pdf',N'1',NULL,N'1',N'40 pages, page 46 du referentiel.',NULL,NULL),
        (N'NPMQ',N'NPMQ',N'Norme professionnelle de management de la qualite',N'CNOEC',N'Arrete ministeriel du 30 mai 2024, publie le 17 juillet 2024, qui abroge l''annexe 3 de l''arrete du 1er septembre 2016',N'A compter du 1er janvier 2025',N'2025',N'15_DOCUMENTATION/npmq-2025.pdf',N'1',NULL,N'1',N'23 pages, page 23 du referentiel. Norme de MANAGEMENT de la qualite, non de maitrise.',NULL,NULL),
        (N'PCG',N'Plan comptable general',N'Reglement ANC n° 2014-03 relatif au plan comptable general',N'ANC',NULL,N'Version consolidee au 1er janvier 2026',N'1er janvier 2026',N'15_DOCUMENTATION/PCG-2026-01-01.pdf',N'1',NULL,N'1',N'183 pages. Verse au dossier par le candidat le 04/09/2026. S''applique aux filiales du groupe, les SCI n''etant pas des OPCI. L''OPCI lui-meme applique le reglement ANC 2021-09.',NULL,NULL),
        (N'REF-OEC',N'Referentiel normatif OEC',N'Referentiel normatif de l''Ordre des experts-comptables',N'CNOEC',NULL,NULL,N'Aout 2025',N'15_DOCUMENTATION/202508Referentiel normatif DEF.pdf',N'1',NULL,N'1',N'284 pages. Porte 11 normes professionnelles et un glossaire des termes et expressions utilises, page 270.',NULL,NULL);
    PRINT 'ref_norme : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'ref_norme : deja chargee, rien a faire.';
GO
