-- ref_ligne_annexe : 189 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[ref_ligne_annexe])
BEGIN
    INSERT INTO dbo.[ref_ligne_annexe] ([article], [code], [libelle], [niveau], [type_ligne], [signe], [racines], [racines_exclues], [sens], [formule], [renvoi], [ordre], [modifie_par], [modifie_le], [globalisable]) VALUES
        (N'332-1',N'ACTIF_NET',N'L''actif net',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'actif net de l''exercice',NULL,N'2',NULL,NULL,N'0'),
        (N'332-1',N'CAPITALISATION',N'La capitalisation unitaire pour chacune des catégories de parts',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'part non distribuée du résultat, divisée par les parts',NULL,N'7',NULL,NULL,N'0'),
        (N'332-1',N'DIST_CESSION',N'La distribution unitaire sur résultat de cession (y compris les acomptes) pour chacune des catégories de parts',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'distribution décidée sur cessions, divisée par les parts',NULL,N'5',NULL,NULL,N'0'),
        (N'332-1',N'DIST_RESULTAT',N'La distribution unitaire sur résultat net (y compris les acomptes) pour chacune des catégories de parts',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'distribution décidée sur résultat net, divisée par les parts',NULL,N'6',NULL,NULL,N'0'),
        (N'332-1',N'NB_PARTS',N'Le nombre de parts pour chacune des catégories de parts',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'parts en circulation',NULL,N'3',NULL,NULL,N'0'),
        (N'332-1',N'STRATEGIE',N'Stratégie d''investissement rappelée du prospectus',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Article 332-1 : selon les informations du prospectus, la strategie d''investissement de l''OPCI est rappelee.',N'1',NULL,NULL,N'0'),
        (N'332-1',N'VL_UNIT',N'La valeur liquidative unitaire pour chacune des catégories de parts',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'actif net divisé par les parts',NULL,N'4',NULL,NULL,N'0'),
        (N'333-1',N'CAPITAL',N'Capital (1)',N'0',N'CALCUL',NULL,N'101,102,103,104,105,106,107,108,109',NULL,N'CREDIT',NULL,N'Le renvoi (1) du modele designe le capital, dont le total final est la somme (1+2).',N'1',NULL,NULL,N'0'),
        (N'333-1',N'CP_TOTAL',N'Total des capitaux propres (1+2)',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'CAPITAL + SD_TOTAL',NULL,N'17',NULL,NULL,N'0'),
        (N'333-1',N'SD',N'Sommes distribuables',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'333-1',N'SD_AC',N'Acomptes versés au cours de l''exercice',N'1',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'10',NULL,NULL,N'0'),
        (N'333-1',N'SD_AC_NET',N'Sur le résultat net',N'2',N'CALCUL',NULL,N'129',N'1293',N'CREDIT',NULL,NULL,N'11',NULL,NULL,N'0'),
        (N'333-1',N'SD_AC_PMV',N'Sur les plus et moins-values réalisées',N'2',N'CALCUL',NULL,N'1293',NULL,N'CREDIT',NULL,NULL,N'12',NULL,NULL,N'0'),
        (N'333-1',N'SD_REG_AC',N'Compte de régularisation sur les acomptes versés',N'1',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'13',NULL,NULL,N'0'),
        (N'333-1',N'SD_REG_AC_NET',N'Sur le résultat net',N'2',N'CALCUL',NULL,N'198',NULL,N'CREDIT',NULL,NULL,N'14',NULL,NULL,N'0'),
        (N'333-1',N'SD_REG_AC_PMV',N'Sur les plus et moins-values réalisées',N'2',N'CALCUL',NULL,N'1983',NULL,N'CREDIT',NULL,NULL,N'15',NULL,NULL,N'0'),
        (N'333-1',N'SD_REG_PMV',N'Compte de régularisation sur le report des plus-values nettes',N'1',N'CALCUL',NULL,N'193',NULL,N'CREDIT',NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'333-1',N'SD_REG_RES',N'Compte de régularisation sur le report des résultats nets antérieurs',N'1',N'CALCUL',NULL,N'191',NULL,N'CREDIT',NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'333-1',N'SD_REPORT_PMV',N'Report des plus-values nettes réalisées',N'1',N'CALCUL',NULL,N'112',NULL,N'CREDIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'333-1',N'SD_REPORT_RES',N'Report des résultats nets antérieurs',N'1',N'CALCUL',NULL,N'111',NULL,N'CREDIT',NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'333-1',N'SD_RES',N'Résultat de l''exercice',N'1',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'7',NULL,NULL,N'0'),
        (N'333-1',N'SD_RES_NET',N'Sur le résultat net',N'2',N'CALCUL',NULL,N'120',N'1202',N'CREDIT',NULL,NULL,N'8',NULL,NULL,N'0'),
        (N'333-1',N'SD_RES_PMV',N'Sur les plus et moins-values réalisées',N'2',N'CALCUL',NULL,N'1202',NULL,N'CREDIT',NULL,NULL,N'9',NULL,NULL,N'0'),
        (N'333-1',N'SD_TOTAL',N'Total des sommes distribuables (2)',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des lignes de sommes distribuables',N'Le renvoi (2) du modele : ce total est la grandeur que le montant decide de la distribution ne peut pas depasser.',N'16',NULL,NULL,N'0'),
        (N'333-2',N'MONTANTS_NETS',N'Montants nets',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'SOUSCRIPTIONS - RACHATS',N'Le modele porte 3 colonnes : nombre de parts ou actions, montants bruts hors frais et commissions, frais et commissions. Le renvoi du tableau precise : frais et commissions percus par l''OPCI et non retrocedes.',N'3',NULL,NULL,N'0'),
        (N'333-2',N'RACHATS',N'Rachats réalisés',N'0',N'CALCUL',NULL,N'1022',NULL,N'DEBIT',N'nombre de parts et montant brut',NULL,N'2',NULL,NULL,N'0'),
        (N'333-2',N'SOUSCRIPTIONS',N'Souscriptions enregistrées',N'0',N'CALCUL',NULL,N'1021',NULL,N'CREDIT',N'nombre de parts et montant brut',NULL,N'1',NULL,NULL,N'0'),
        (N'333-3',N'AC_CESSIONS',N'sur cessions d''actifs',N'1',N'CALCUL',N'-',N'1293',NULL,N'DEBIT',NULL,NULL,N'20',NULL,NULL,N'0'),
        (N'333-3',N'AC_RES_NET',N'sur résultat net',N'1',N'CALCUL',N'-',N'1291',NULL,N'DEBIT',NULL,NULL,N'19',NULL,NULL,N'0'),
        (N'333-3',N'ACOMPTES',N'Acomptes versés au cours de l''exercice avant comptes de régularisations',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'18',NULL,NULL,N'0'),
        (N'333-3',N'AN_DEBUT',N'Actif net (= capitaux propres) en début d''exercice',N'0',N'CALCUL',N'+',NULL,NULL,NULL,N'actif net de l''arrêté précédent',NULL,N'1',NULL,NULL,N'0'),
        (N'333-3',N'AN_FIN',N'Actif net (= capitaux propres) en fin d''exercice',N'0',N'TOTAL',N'=',NULL,NULL,NULL,N'somme algébrique des lignes ci-dessus',NULL,N'23',NULL,NULL,N'0'),
        (N'333-3',N'AUTRES',N'Autres éléments',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Renvoi 1 du modele : le contenu de cette ligne fait l''objet d''une explication precise de la part de l''OPCI, versements en garantie, provisions pour risques et charges et autres variations d''actif net non detaillees ci-dessus.',N'22',NULL,NULL,N'0'),
        (N'333-3',N'CHANGE',N'Différences de change',N'0',N'CALCUL',N'+/-',N'106',NULL,N'CREDIT',NULL,NULL,N'7',NULL,NULL,N'0'),
        (N'333-3',N'DE_FIN_N',N'Différence d''estimation exercice N :',N'1',N'CALCUL',NULL,N'1053',NULL,N'CREDIT',NULL,NULL,N'12',NULL,NULL,N'0'),
        (N'333-3',N'DE_FIN_N1',N'Différence d''estimation exercice N-1 :',N'1',N'CALCUL',NULL,N'1053',NULL,N'CREDIT',N'solde de l''arrêté précédent',NULL,N'13',NULL,NULL,N'0'),
        (N'333-3',N'DE_IMMO_N',N'Différence d''estimation exercice N :',N'1',N'CALCUL',NULL,N'1052',NULL,N'CREDIT',NULL,NULL,N'9',NULL,NULL,N'0'),
        (N'333-3',N'DE_IMMO_N1',N'Différence d''estimation exercice N-1 :',N'1',N'CALCUL',NULL,N'1052',NULL,N'CREDIT',N'solde de l''arrêté précédent',NULL,N'10',NULL,NULL,N'0'),
        (N'333-3',N'DISTRIB_PREC',N'Distribution de l''exercice précédent',N'0',N'CALCUL',N'-',NULL,NULL,NULL,N'distribution mise en paiement sur l''exercice',N'Le modele porte ici le renvoi 1, qui vise aussi la ligne « Autres elements ».',N'14',NULL,NULL,N'0'),
        (N'333-3',N'FRAIS_ACQ',N'Frais liés à l''acquisition',N'0',N'RUBRIQUE',N'-',NULL,NULL,NULL,NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'333-3',N'FRAIS_ACQ_N',N'Frais d''acquisition de l''exercice',N'1',N'CALCUL',NULL,N'1041',NULL,N'DEBIT',NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'333-3',N'FRAIS_ACQ_RES',N'Frais d''acquisition rapportés au compte de résultat sur l''exercice',N'1',N'CALCUL',NULL,N'1049',NULL,N'DEBIT',NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'333-3',N'FUSION',N'Écart résultant d''une fusion ou transmission universelle de patrimoine',N'0',N'CALCUL',N'+/-',N'1081',NULL,N'CREDIT',NULL,NULL,N'21',NULL,NULL,N'0'),
        (N'333-3',N'RACHATS',N'Rachats (sous déduction des commissions de rachat acquises à l''OPCI)',N'0',N'CALCUL',N'-',N'1022,1032',NULL,N'DEBIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'333-3',N'RES_NET',N'Résultat net avant comptes de régularisations',N'1',N'CALCUL',NULL,N'1201',NULL,N'CREDIT',NULL,NULL,N'16',NULL,NULL,N'0'),
        (N'333-3',N'RES_PMV',N'Plus et moins-values réalisées avant comptes de régularisations',N'1',N'CALCUL',NULL,N'1202',NULL,N'CREDIT',NULL,NULL,N'17',NULL,NULL,N'0'),
        (N'333-3',N'RESULTAT',N'Résultat de l''exercice avant comptes de régularisations',N'0',N'RUBRIQUE',N'+/-',NULL,NULL,NULL,NULL,NULL,N'15',NULL,NULL,N'0'),
        (N'333-3',N'SOUSCRIPTIONS',N'Souscriptions (y compris les commissions de souscriptions, droits et taxes acquis à l''OPCI)',N'0',N'CALCUL',N'+',N'1021,1031',NULL,N'CREDIT',NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'333-3',N'VAR_DE_FIN',N'Variation de la différence d''estimation des dépôts et instruments financiers non immobiliers',N'0',N'CALCUL',N'+/-',N'1053',NULL,N'CREDIT',N'différence N moins différence N-1',NULL,N'11',NULL,NULL,N'0'),
        (N'333-3',N'VAR_DE_IMMO',N'Variation de la différence d''estimation des actifs à caractère immobilier',N'0',N'CALCUL',N'+/-',N'1052',NULL,N'CREDIT',N'différence N moins différence N-1',NULL,N'8',NULL,NULL,N'0'),
        (N'334-1',N'PRINCIPE',N'Objectif des tableaux de la section : refléter les expositions de l''OPCI aux actifs à caractère immobilier à la date de clôture',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'334-2',N'AUTRES',N'Autres',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'334-2',N'DROITS_REELS',N'Autres droits réels',N'1',N'CALCUL',NULL,N'23,273',NULL,N'DEBIT',NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'334-2',N'EN_COURS',N'Immeubles en cours de construction',N'1',N'CALCUL',NULL,N'221,228,272',NULL,N'DEBIT',NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'334-2',N'SOL_AUTRUI',N'Constructions sur sol d''autrui',N'1',N'CALCUL',NULL,N'214',NULL,N'DEBIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'334-2',N'TERRAINS_CONSTR',N'Terrains et constructions',N'1',N'CALCUL',NULL,N'213,271',NULL,N'DEBIT',NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'334-2',N'TERRAINS_NUS',N'Terrains nus',N'1',N'CALCUL',NULL,N'211',NULL,N'DEBIT',NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'334-2',N'TOTAL',N'Total',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des natures',N'Le modele porte 6 colonnes : exercice N-1, augmentations, diminutions, variation des differences d''estimation, exercice N, et frais. Article 334-2 : les Frais comprennent les frais d''acquisition cumules inscrits en classe 1.',N'7',NULL,NULL,N'0'),
        (N'334-2',N'TOTAL_HORS_FRAIS',N'Total frais exclus',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'TOTAL sans la colonne des frais',N'Les frais d''acquisition sont enregistres directement en capital, article 211-3 : ils sont donc hors du cout d''acquisition, et le modele les isole.',N'8',NULL,NULL,N'0'),
        (N'334-3',N'ASSIETTE',N'Valeur des biens pris en crédit-bail au moment de la signature du contrat (assiette d''origine du contrat)',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'334-3',N'PRIX_RESIDUEL',N'Prix d''achat résiduel de ces biens stipulé au contrat',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'7',NULL,NULL,N'0'),
        (N'334-3',N'REDEVANCES_CUM',N'Montant cumulé des redevances des exercices précédents',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'334-3',N'REDEVANCES_N',N'Montant des redevances afférentes à l''exercice',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'334-3',N'RESTANT_1_5ANS',N'Redevances restant à payer, à plus d''un an et cinq ans au plus',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'334-3',N'RESTANT_1AN',N'Redevances restant à payer, à un an au plus',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'334-3',N'RESTANT_5ANS',N'Redevances restant à payer, à plus de cinq ans',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'334-3',N'TOTAL',N'Total',N'0',N'TOTAL',NULL,N'243,245,274',NULL,N'DEBIT',NULL,N'Les informations sont ventilees selon les postes du bilan dont auraient releve les biens concernes.',N'8',NULL,NULL,N'0'),
        (N'334-5',N'PARTS_2',N'Parts des sociétés de personnes (2° du I, art. L214-36)',N'1',N'CALCUL',NULL,N'252',NULL,N'DEBIT',NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'334-5',N'PARTS_3',N'Parts et actions des sociétés (3° du I, art. L214-36)',N'1',N'CALCUL',NULL,N'254',NULL,N'DEBIT',NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'334-5',N'SECTEURS',N'Ventilation de la valeur actuelle par secteur d''activité et par secteur géographique',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Article 334-5 : l''OPCI determine les secteurs adaptes a la composition de son patrimoine. A titre INDICATIF, bureaux, habitations, locaux d''activite, entrepots, commerces ; et Paris, Ile de France, province, etranger. Ces listes ne sont pas contraintes, le texte les donnant a titre indicatif.',N'5',NULL,NULL,N'0'),
        (N'334-5',N'TOTAL',N'Total',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'PARTS_2 + PARTS_3',N'Le modele porte 6 colonnes : exercice N-1, cessions, acquisitions, variation des differences d''estimation, exercice N, et frais.',N'3',NULL,NULL,N'0'),
        (N'334-5',N'TOTAL_HORS_FRAIS',N'Total frais exclus',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'TOTAL sans la colonne des frais',NULL,N'4',NULL,NULL,N'0'),
        (N'334-6',N'COMPTES_COURANTS',N'Comptes courants dans les filiales et participations',N'1',N'CALCUL',NULL,N'266,276',NULL,N'DEBIT',NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'334-6',N'ECHEANCE',N'Échéance à la clôture de l''exercice',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Article 334-6 : le cas echeant, pour les comptes courants, il est precise leur echeance a la cloture de l''exercice. Article 213-4 : les avances sont evaluees pour leur montant nominal, majore des interets courus, quelle que soit leur echeance.',N'2',NULL,NULL,N'0'),
        (N'334-6',N'TOTAL',N'Total',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des comptes courants',NULL,N'3',NULL,NULL,N'0'),
        (N'334-7',N'ACTIONS_4',N'Actions négociées sur un marché réglementé (4° du I, art. L214-36 id.)',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'10',NULL,NULL,N'0'),
        (N'334-7',N'AUTRES',N'Autres',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'334-7',N'AUTRES_IMMO',N'Autres actifs immobiliers',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'12',NULL,NULL,N'0'),
        (N'334-7',N'DROITS_REELS',N'Droits réels',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'334-7',N'EN_COURS',N'Immeubles en cours de construction',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'334-7',N'OPCI_5',N'Parts ou actions d''OPCI et organismes équivalents (5° du I, art. L214-36 id.)',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'11',NULL,NULL,N'0'),
        (N'334-7',N'PARTS_2',N'Parts des sociétés de personnes (2° du I, art. L214-36 du COMOFI)',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'8',NULL,NULL,N'0'),
        (N'334-7',N'PARTS_3',N'Parts et actions des sociétés visées au 3° du I, art. L214-36 id.',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'9',NULL,NULL,N'0'),
        (N'334-7',N'SOL_AUTRUI',N'Constructions sur sol d''autrui',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'334-7',N'TERRAINS_CONSTR',N'Terrains et constructions',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'334-7',N'TERRAINS_NUS',N'Terrains nus',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'334-7',N'TOTAL_AUTRES',N'Total autres actifs à caractère immobilier',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des 5 categories',NULL,N'13',NULL,NULL,N'0'),
        (N'334-7',N'TOTAL_GENERAL',N'Total actifs à caractère immobilier',N'0',N'TOTAL',NULL,N'761,661',NULL,N'CREDIT',N'TOTAL_IMMEUBLES + TOTAL_AUTRES',N'Le modele porte 4 colonnes : plus-values, moins-values, plus et moins-values N, plus et moins-values N-1. Le total se rapproche des comptes 761 et 661.',N'14',NULL,NULL,N'0'),
        (N'334-7',N'TOTAL_IMMEUBLES',N'Total Immeubles en cours, construits ou acquis et droits réels',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des 6 natures',NULL,N'7',NULL,NULL,N'0'),
        (N'334-8',N'RENVOI_2020_07',N'Expositions liées aux actifs financiers, selon les modèles du règlement relatif aux comptes annuels des OPCCV',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Article 334-8 : le cas echeant, lorsque l''OPCI gere des actifs financiers, il presente les expositions liees a ces actifs selon leur nature en reprenant les modeles correspondants du reglement relatif aux comptes annuels des organismes de placement collectif a capital variable, soit le reglement ANC 2020-07, Livre I du recueil.',N'1',NULL,NULL,N'0'),
        (N'335-1',N'PRINCIPE',N'Les autres informations relatives au bilan et au compte de résultat, dès lors qu''elles sont significatives',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Article 335-1 : les modeles de tableaux presentes ci-apres sont fournis A TITRE INDICATIF ; ces informations peuvent etre developpees ou synthetisees en tant que de besoin.',N'1',NULL,NULL,N'0'),
        (N'335-10',N'F_1',N'Frais de gestion',N'1',N'CALCUL',NULL,N'611',NULL,N'DEBIT',NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'335-10',N'F_2',N'Frais de fonctionnement externes',N'1',N'CALCUL',NULL,N'612',NULL,N'DEBIT',NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'335-10',N'F_3',N'Frais d''audit, d''études',N'1',N'CALCUL',NULL,N'622',NULL,N'DEBIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'335-10',N'F_4',N'Impôts et taxes',N'1',N'CALCUL',NULL,N'629',NULL,N'DEBIT',NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'335-10',N'F_5',N'Autres charges',N'1',N'CALCUL',NULL,N'615',NULL,N'DEBIT',NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'335-10',N'F_6',N'Commissions de surperformance',N'1',N'CALCUL',NULL,N'617',NULL,N'DEBIT',NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'335-10',N'TOTAL',N'Total général',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des frais',NULL,N'7',NULL,NULL,N'0'),
        (N'335-12',N'I',N'I. Affectation des sommes distribuables au titre du résultat net',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'335-12',N'I_A',N'Affectation des sommes distribuables',N'1',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'7',NULL,NULL,N'0'),
        (N'335-12',N'I_A_1',N'Distribution',N'2',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'La distribution decidee est portee par dbo.decision_distribution, bornee par l''obligation minimale de 85 % et le total distribuable, article L. 214-69, II, 1°.',N'8',NULL,NULL,N'0'),
        (N'335-12',N'I_A_2',N'Report à nouveau du résultat net',N'2',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'9',NULL,NULL,N'0'),
        (N'335-12',N'I_A_3',N'Capitalisation',N'2',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'10',NULL,NULL,N'0'),
        (N'335-12',N'I_A_T',N'Total des sommes affectées au titre du résultat net',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'I_A_1 + I_A_2 + I_A_3',N'Ce total doit egaler celui des sommes distribuables : une somme distribuable non affectee serait sans emploi.',N'11',NULL,NULL,N'0'),
        (N'335-12',N'I_D',N'Détail des sommes distribuables au titre du résultat net',N'1',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'335-12',N'I_D_1',N'Résultat net de l''exercice après régularisations',N'2',N'CALCUL',NULL,N'120,772',N'1202',N'CREDIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'335-12',N'I_D_2',N'Report des résultats nets antérieurs après régularisations',N'2',N'CALCUL',NULL,N'111,191',NULL,N'CREDIT',NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'335-12',N'I_D_3',N'Acomptes versés sur résultat net de l''exercice après régularisations',N'2',N'CALCUL',NULL,N'1291,198',NULL,N'DEBIT',NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'335-12',N'I_D_T',N'Total des sommes distribuables au titre du résultat net',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'I_D_1 + I_D_2 - I_D_3',NULL,N'6',NULL,NULL,N'0'),
        (N'335-12',N'II',N'II. Affectation des sommes distribuables aux titres des plus et moins-values réalisées nettes',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'12',NULL,NULL,N'0'),
        (N'335-12',N'II_A',N'Affectation des sommes distribuables',N'1',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'18',NULL,NULL,N'0'),
        (N'335-12',N'II_A_1',N'Distribution',N'2',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Obligation minimale de 50 % au titre de l''exercice suivant, article L. 214-69, II, 2°.',N'19',NULL,NULL,N'0'),
        (N'335-12',N'II_A_2',N'Report à nouveau des plus-values réalisées nettes',N'2',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'20',NULL,NULL,N'0'),
        (N'335-12',N'II_A_3',N'Capitalisation',N'2',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'21',NULL,NULL,N'0'),
        (N'335-12',N'II_A_T',N'Total des sommes affectées au titre des plus et moins-values réalisées nettes',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'II_A_1 + II_A_2 + II_A_3',NULL,N'22',NULL,NULL,N'0'),
        (N'335-12',N'II_D',N'Détail des sommes distribuables au titre des plus et moins-values réalisées nettes',N'1',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'13',NULL,NULL,N'0'),
        (N'335-12',N'II_D_1',N'Plus et moins-values nettes de l''exercice après régularisations',N'2',N'CALCUL',NULL,N'1202,776',NULL,N'CREDIT',NULL,NULL,N'14',NULL,NULL,N'0'),
        (N'335-12',N'II_D_2',N'Report des plus-values nettes réalisées après régularisations',N'2',N'CALCUL',NULL,N'112,193',NULL,N'CREDIT',NULL,NULL,N'15',NULL,NULL,N'0'),
        (N'335-12',N'II_D_3',N'Acomptes versés sur plus et moins-values nettes après régularisations',N'2',N'CALCUL',NULL,N'1293',NULL,N'DEBIT',NULL,NULL,N'16',NULL,NULL,N'0'),
        (N'335-12',N'II_D_T',N'Total des sommes distribuables au titre des plus et moins-values réalisées nettes',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'II_D_1 + II_D_2 - II_D_3',NULL,N'17',NULL,NULL,N'0'),
        (N'335-2',N'AC',N'Autres créances',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'335-2',N'AC_1',N'Intérêts ou dividendes à recevoir',N'1',N'CALCUL',NULL,N'413',NULL,N'DEBIT',NULL,NULL,N'7',NULL,NULL,N'0'),
        (N'335-2',N'AC_2',N'État et autres collectivités',N'1',N'CALCUL',NULL,N'441,445,447,448',NULL,N'DEBIT',NULL,NULL,N'8',NULL,NULL,N'0'),
        (N'335-2',N'AC_3',N'Syndics',N'1',N'CALCUL',NULL,N'467',NULL,N'DEBIT',NULL,NULL,N'9',NULL,NULL,N'0'),
        (N'335-2',N'AC_4',N'Autres débiteurs',N'1',N'CALCUL',NULL,N'461,47',NULL,N'DEBIT',NULL,NULL,N'10',NULL,NULL,N'0'),
        (N'335-2',N'AC_5',N'Charges constatées d''avance',N'1',N'CALCUL',NULL,N'486',NULL,N'DEBIT',NULL,NULL,N'11',NULL,NULL,N'0'),
        (N'335-2',N'AC_6',N'Dépréciations des autres créances',N'1',N'CALCUL',NULL,N'496',NULL,N'CREDIT',NULL,NULL,N'12',NULL,NULL,N'0'),
        (N'335-2',N'AC_ST',N'Sous-total',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des autres créances',NULL,N'13',NULL,NULL,N'0'),
        (N'335-2',N'CL',N'Créances locataires',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'335-2',N'CL_1',N'Créances locataires',N'1',N'CALCUL',NULL,N'421,423',NULL,N'DEBIT',NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'335-2',N'CL_2',N'Créances faisant l''objet de dépréciations (créances douteuses)',N'1',N'CALCUL',NULL,N'422',NULL,N'DEBIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'335-2',N'CL_3',N'Dépréciations des créances locataires',N'1',N'CALCUL',NULL,N'491',NULL,N'CREDIT',NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'335-2',N'CL_ST',N'Sous-total',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'CL_1 + CL_2 - CL_3',NULL,N'5',NULL,NULL,N'0'),
        (N'335-2',N'DEP_AC',N'Dépréciations des autres créances',N'1',N'CALCUL',NULL,N'496',NULL,N'CREDIT',NULL,NULL,N'16',NULL,NULL,N'0'),
        (N'335-2',N'DEP_CL',N'Dépréciations des créances locataires',N'1',N'CALCUL',NULL,N'491',NULL,N'CREDIT',NULL,N'Le second tableau de l''article 335-2 porte 4 colonnes : situation N-1, dotations de l''exercice, reprises de l''exercice, situation N.',N'15',NULL,NULL,N'0'),
        (N'335-2',N'DEP_TOTAL',N'Total',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'DEP_CL + DEP_AC',NULL,N'17',NULL,NULL,N'0'),
        (N'335-2',N'TOTAL',N'Total',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'CL_ST + AC_ST',NULL,N'14',NULL,NULL,N'0'),
        (N'335-3',N'PROVISIONS',N'Provisions pour risques et charges',N'1',N'CALCUL',NULL,N'497',NULL,N'CREDIT',NULL,N'Le modele porte 4 colonnes : situation N-1, dotations de l''exercice, reprises de l''exercice, situation N.',N'1',NULL,NULL,N'0'),
        (N'335-3',N'TOTAL',N'Total',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des provisions',NULL,N'2',NULL,NULL,N'0'),
        (N'335-6',N'D_1',N'Locataires créditeurs',N'1',N'CALCUL',NULL,N'429',NULL,N'CREDIT',NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'335-6',N'D_2',N'Fournisseurs et comptes rattachés',N'1',N'CALCUL',NULL,N'405,408,409',NULL,N'CREDIT',NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'335-6',N'D_3',N'État et autres collectivités',N'1',N'CALCUL',NULL,N'445,447,448',NULL,N'CREDIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'335-6',N'D_4',N'Autres créditeurs',N'1',N'CALCUL',NULL,N'467,47',NULL,N'CREDIT',NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'335-6',N'D_5',N'Produits constatés d''avance',N'1',N'CALCUL',NULL,N'487,488',NULL,N'CREDIT',NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'335-6',N'TOTAL',N'Total des autres dettes d''exploitation',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des dettes',NULL,N'6',NULL,NULL,N'0'),
        (N'335-8',N'C',N'Charges sur opérations financières',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'12',NULL,NULL,N'0'),
        (N'335-8',N'C_1',N'Charges sur opérations financières',N'1',N'CALCUL',NULL,N'60',N'604,605,608',N'DEBIT',NULL,NULL,N'13',NULL,NULL,N'0'),
        (N'335-8',N'C_2',N'Charges sur instruments financiers à terme',N'1',N'CALCUL',NULL,N'605',NULL,N'DEBIT',NULL,NULL,N'14',NULL,NULL,N'0'),
        (N'335-8',N'C_3',N'Charges sur opérations temporaires sur titres',N'1',N'CALCUL',NULL,N'604',NULL,N'DEBIT',NULL,NULL,N'15',NULL,NULL,N'0'),
        (N'335-8',N'C_4',N'Charges sur emprunts',N'1',N'CALCUL',NULL,N'608',NULL,N'DEBIT',NULL,NULL,N'16',NULL,NULL,N'0'),
        (N'335-8',N'C_5',N'Charges sur autres actifs et passifs éligibles',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'17',NULL,NULL,N'0'),
        (N'335-8',N'C_6',N'Charges sur passifs de financement',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'18',NULL,NULL,N'0'),
        (N'335-8',N'C_7',N'Autres charges financières',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'19',NULL,NULL,N'0'),
        (N'335-8',N'C_ST',N'Sous-total charges sur opérations financières',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des charges',NULL,N'20',NULL,NULL,N'0'),
        (N'335-8',N'P',N'Produits sur opérations financières',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'335-8',N'P_1',N'Produits sur actions',N'1',N'CALCUL',NULL,N'700',NULL,N'CREDIT',NULL,NULL,N'2',NULL,NULL,N'0'),
        (N'335-8',N'P_2',N'Produits sur obligations',N'1',N'CALCUL',NULL,N'701',NULL,N'CREDIT',NULL,NULL,N'3',NULL,NULL,N'0'),
        (N'335-8',N'P_3',N'Produits sur titres de créance',N'1',N'CALCUL',NULL,N'702',NULL,N'CREDIT',NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'335-8',N'P_4',N'Produits sur des parts d''OPC',N'1',N'CALCUL',NULL,N'703',NULL,N'CREDIT',NULL,NULL,N'5',NULL,NULL,N'0'),
        (N'335-8',N'P_5',N'Produits sur instruments financiers à terme',N'1',N'CALCUL',NULL,N'705',NULL,N'CREDIT',NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'335-8',N'P_6',N'Produits sur opérations temporaires sur titres',N'1',N'CALCUL',NULL,N'704',NULL,N'CREDIT',NULL,NULL,N'7',NULL,NULL,N'0'),
        (N'335-8',N'P_7',N'Produits sur prêts et créances',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'8',NULL,NULL,N'0'),
        (N'335-8',N'P_8',N'Produits sur autres actifs et passifs éligibles',N'1',N'CALCUL',NULL,N'706',NULL,N'CREDIT',NULL,NULL,N'9',NULL,NULL,N'0'),
        (N'335-8',N'P_9',N'Autres produits financiers',N'1',N'CALCUL',NULL,N'708',NULL,N'CREDIT',NULL,NULL,N'10',NULL,NULL,N'0'),
        (N'335-8',N'P_ST',N'Sous-total Produits sur opérations financières',N'1',N'TOTAL',NULL,NULL,NULL,NULL,N'somme des produits',NULL,N'11',NULL,NULL,N'0'),
        (N'335-8',N'TOTAL',N'Total Revenus financiers nets',N'0',N'TOTAL',NULL,NULL,NULL,NULL,N'P_ST - C_ST',N'Article 335-8 : le cas echeant les autres produits financiers et autres charges financieres sont detailles par nature.',N'21',NULL,NULL,N'0'),
        (N'335-9',N'DETAIL',N'Le cas échéant les autres produits et charges sont détaillés par nature',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'1',NULL,NULL,N'0'),
        (N'336-1',N'PRINCIPE',N'L''inventaire du portefeuille d''un OPCI est établi par poste du bilan',N'0',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Article 336-1 : la charpente des 2 inventaires suit les postes du bilan actif de l''article 321-2, ce ne sont pas des listes libres.',N'1',NULL,NULL,N'0'),
        (N'336-2',N'AUTRES_LIBELLE',N'Libellé',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'libellé de l''actif',NULL,N'13',NULL,NULL,N'0'),
        (N'336-2',N'AUTRES_PCT',N'% de l''actif net',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'valeur actuelle divisée par l''actif net',NULL,N'16',NULL,NULL,N'0'),
        (N'336-2',N'AUTRES_QUANTITE',N'Quantité / nominal',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'quantité ou nominal de l''actif',NULL,N'14',NULL,NULL,N'0'),
        (N'336-2',N'AUTRES_VALEUR',N'Valeur actuelle',N'1',N'CALCUL',NULL,N'265,266,276',NULL,N'DEBIT',NULL,NULL,N'15',NULL,NULL,N'0'),
        (N'336-2',N'FIL_CONTROLEES',N'Filiales ou participations contrôlées au sens de l''article R214-83 du code monétaire et financier',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,N'L''article R. 214-83 du CMF N''A PAS ETE LU : le critere de controle est a saisir, et aucune regle de controle n''est ecrite faute d''avoir lu le texte.',N'5',NULL,NULL,N'0'),
        (N'336-2',N'FIL_COUT',N'Coût de revient des titres frais exclus (2)',N'1',N'CALCUL',NULL,N'252,254',NULL,N'DEBIT',NULL,N'Renvoi (2) : frais exclus, les frais d''acquisition de titres etant enregistres en capital, article 212-3.',N'10',NULL,NULL,N'0'),
        (N'336-2',N'FIL_DATE',N'Date d''acquisition des parts ou des sous-jacents',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'9',NULL,NULL,N'0'),
        (N'336-2',N'FIL_DIFFERENCE',N'Différence d''estimation (3) - (2)',N'1',N'CALCUL',NULL,N'275',NULL,N'DEBIT',N'FIL_VALEUR - FIL_COUT',N'Le modele definit lui-meme la difference comme la soustraction des colonnes (3) et (2), ce qui donne un controle calculable.',N'12',NULL,NULL,N'0'),
        (N'336-2',N'FIL_NATURE',N'Nature des immeubles détenus (1)',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,N'Renvoi (1) du modele : preciser le nombre et la nature des immeubles detenus par la filiale ou participation, type de bien, terrain nu, terrain et construction, construction sur sol d''autrui, autre droit reel, immeuble en cours, secteur d''activite, localisation.',N'7',NULL,NULL,N'0'),
        (N'336-2',N'FIL_NON_CONTROLEES',N'Filiales ou participations non contrôlées au sens de l''article R214-83 du code monétaire et financier',N'0',N'RUBRIQUE',NULL,NULL,NULL,NULL,NULL,NULL,N'6',NULL,NULL,N'0'),
        (N'336-2',N'FIL_SECTEUR',N'Secteur d''activité et localisation',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'8',NULL,NULL,N'0'),
        (N'336-2',N'FIL_VALEUR',N'Valeur actuelle des titres comptabilisée (3)',N'1',N'CALCUL',NULL,N'252,254,275',NULL,N'DEBIT',NULL,NULL,N'11',NULL,NULL,N'0'),
        (N'336-2',N'IMM_LIBELLE',N'Libellé : adresse, surface, secteur, date d''acquisition',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'adresse, surface_m2, secteur et date_acquisition de l''actif',N'Les 3 premieres colonnes sont saisies sur dbo.actif depuis le script 113 ; la date d''acquisition y figurait deja.',N'1',NULL,NULL,N'0'),
        (N'336-2',N'IMM_PCT_ACTIF_NET',N'% de l''actif net',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'valeur actuelle divisée par l''actif net',N'Article 336-2 : globalisable, comme la valeur actuelle.',N'4',NULL,NULL,N'1'),
        (N'336-2',N'IMM_PRIX_REVIENT',N'Prix de revient',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'prix_de_revient de l''actif',NULL,N'2',NULL,NULL,N'0'),
        (N'336-2',N'IMM_VALEUR_ACTUELLE',N'Valeur actuelle',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'valeur actuelle de l''actif',N'Article 336-2 : la valeur actuelle et le % de l''actif net PEUVENT ETRE DONNES DE FACON GLOBALE, et non actif par actif.',N'3',NULL,NULL,N'1'),
        (N'336-3',N'DEVISE',N'Devise de cotation',N'1',N'SAISIE',NULL,NULL,NULL,NULL,NULL,NULL,N'4',NULL,NULL,N'0'),
        (N'336-3',N'LIBELLE',N'Libellé',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'libellé de l''instrument',NULL,N'1',NULL,NULL,N'0'),
        (N'336-3',N'PCT',N'% de l''actif net',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'valeur actuelle divisée par l''actif net',NULL,N'5',NULL,NULL,N'0'),
        (N'336-3',N'QUANTITE',N'Quantité / nominal',N'1',N'CALCUL',NULL,NULL,NULL,NULL,N'quantité ou nominal',NULL,N'2',NULL,NULL,N'0'),
        (N'336-3',N'VALEUR',N'Valeur actuelle',N'1',N'CALCUL',NULL,N'30,31,32,33,34,35,36',NULL,N'DEBIT',NULL,NULL,N'3',NULL,NULL,N'0');
    PRINT 'ref_ligne_annexe : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'ref_ligne_annexe : deja chargee, rien a faire.';
GO
