-- ref_piece_attendue : 77 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[ref_piece_attendue])
BEGIN
    INSERT INTO dbo.[ref_piece_attendue] ([id], [cycle], [phase], [libelle], [obligatoire], [periodicite], [racine_declenchante], [ordre], [modifie_par], [modifie_le], [en_vigueur_depuis]) VALUES
        (N'1',N'IMMO',NULL,N'Rapport d''expertise signé',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'2',N'IMMO',NULL,N'Bail et avenants',N'1',N'EVENEMENT',N'721',N'2',NULL,NULL,N'2023-12-31'),
        (N'3',N'IMMO',NULL,N'Titre de propriété',N'1',N'PERMANENT',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'4',N'IMMO',NULL,N'Décompte définitif du notaire sur l''acquisition',N'1',N'EVENEMENT',N'21',N'4',NULL,NULL,N'2023-12-31'),
        (N'5',N'IMMO',NULL,N'État locatif à la date d''arrêté',N'1',N'ARRETE',NULL,N'5',NULL,NULL,N'2023-12-31'),
        (N'6',N'IMMO',NULL,N'Contrat de crédit-bail et échéancier des redevances',N'1',N'EVENEMENT',N'24',N'6',NULL,NULL,N'2023-12-31'),
        (N'7',N'IMMO',NULL,N'Contrat de rente viagère et document d''équité actuarielle',N'1',N'EVENEMENT',N'291',N'7',NULL,NULL,N'2023-12-31'),
        (N'8',N'IMMO',NULL,N'Procès-verbal de réception des travaux',N'1',N'EVENEMENT',N'626',N'8',NULL,NULL,N'2023-12-31'),
        (N'9',N'IMMO',NULL,N'Contrat de vente en l''état futur d''achèvement et échéancier des appels de fonds',N'1',N'EVENEMENT',N'221',N'9',NULL,NULL,N'2023-12-31'),
        (N'10',N'IMMO',NULL,N'Convention de garantie locative',N'1',N'EVENEMENT',N'723',N'10',NULL,NULL,N'2023-12-31'),
        (N'11',N'PART',NULL,N'Comptes annuels des filiales',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'12',N'PART',NULL,N'Procès-verbaux d''assemblée générale des filiales',N'1',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'13',N'PART',NULL,N'Statuts des entités détenues et pièce établissant la quote-part de détention',N'1',N'PERMANENT',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'14',N'PART',NULL,N'Ordre de mouvement de titres et attestation de transfert de propriété',N'1',N'EVENEMENT',N'25',N'4',NULL,NULL,N'2023-12-31'),
        (N'15',N'PART',NULL,N'Convention de compte courant d''associé',N'1',N'EVENEMENT',N'266',N'5',NULL,NULL,N'2023-12-31'),
        (N'16',N'PART',NULL,N'Décision d''abandon de compte courant',N'1',N'EVENEMENT',N'661',N'6',NULL,NULL,N'2023-12-31'),
        (N'17',N'PART',NULL,N'Engagement de couverture des pertes de l''entité détenue',N'1',N'EVENEMENT',N'295',N'7',NULL,NULL,N'2023-12-31'),
        (N'18',N'PART',NULL,N'Situation comptable intermédiaire des entités détenues',N'0',N'ARRETE',NULL,N'8',NULL,NULL,N'2023-12-31'),
        (N'19',N'PART',NULL,N'Confirmation du solde réciproque du compte courant par l''entité détenue',N'1',N'ARRETE',NULL,N'9',NULL,NULL,N'2023-12-31'),
        (N'20',N'PART',NULL,N'Relevé des dépôts et cautionnements versés',N'1',N'ARRETE',NULL,N'10',NULL,NULL,N'2023-12-31'),
        (N'21',N'VALO',NULL,N'Rapport du comité de valorisation',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'22',N'VALO',NULL,N'Attestation d''indépendance de l''évaluateur externe',N'1',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'23',N'VALO',NULL,N'Note des paramètres du modèle financier de valorisation',N'0',N'ARRETE',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'24',N'VALO',NULL,N'État des différences d''estimation par actif',N'1',N'ARRETE',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'25',N'VALO',NULL,N'État de calcul de la valeur liquidative de l''arrêté',N'1',N'ARRETE',NULL,N'5',NULL,NULL,N'2023-12-31'),
        (N'26',N'CAPITAL',NULL,N'Bons de souscription et de rachat',N'1',N'EVENEMENT',N'45',N'1',NULL,NULL,N'2023-12-31'),
        (N'27',N'CAPITAL',NULL,N'Registre des porteurs de parts',N'1',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'28',N'CAPITAL',NULL,N'Attestation du dépositaire sur le nombre de parts en circulation',N'1',N'ARRETE',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'29',N'CAPITAL',NULL,N'État des commissions de souscription et de rachat perçues et rétrocédées',N'1',N'ARRETE',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'30',N'CAPITAL',NULL,N'État des frais d''acquisition par actif',N'1',N'ARRETE',NULL,N'5',NULL,NULL,N'2023-12-31'),
        (N'31',N'AFFECT',NULL,N'Procès-verbal arrêtant l''affectation des sommes distribuables',N'1',N'EVENEMENT',N'120',N'1',NULL,NULL,N'2023-12-31'),
        (N'32',N'AFFECT',NULL,N'Avis de paiement des acomptes versés',N'1',N'EVENEMENT',N'129',N'2',NULL,NULL,N'2023-12-31'),
        (N'33',N'AFFECT',NULL,N'État de calcul des sommes distribuables',N'1',N'ARRETE',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'34',N'AFFECT',NULL,N'Clef d''affectation des frais de gestion entre les catégories de revenus',N'1',N'PERMANENT',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'35',N'AFFECT',NULL,N'État de suivi des obligations de distribution non servies',N'1',N'ARRETE',NULL,N'5',NULL,NULL,N'2023-12-31'),
        (N'36',N'AFFECT',NULL,N'État des produits distribués par les entités détenues, entité par entité',N'1',N'ARRETE',NULL,N'6',NULL,NULL,N'2023-12-31'),
        (N'37',N'FIN',NULL,N'Relevé de portefeuille du dépositaire',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'38',N'FIN',NULL,N'État de valorisation des instruments financiers à terme',N'1',N'EVENEMENT',N'35',N'2',NULL,NULL,N'2023-12-31'),
        (N'39',N'FIN',NULL,N'Contrat de dépôt à terme',N'1',N'EVENEMENT',N'36',N'3',NULL,NULL,N'2023-12-31'),
        (N'40',N'FIN',NULL,N'Avis d''opéré des acquisitions et cessions d''instruments financiers',N'1',N'ARRETE',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'41',N'TRESO',NULL,N'Relevés de banque de la période',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'42',N'TRESO',NULL,N'Rapprochements bancaires',N'1',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'43',N'TRESO',NULL,N'Contrat d''emprunt à caractère immobilier et son échéancier',N'1',N'EVENEMENT',N'512',N'3',NULL,NULL,N'2023-12-31'),
        (N'44',N'TRESO',NULL,N'Contrat des autres emprunts et dettes financières',N'1',N'EVENEMENT',N'513',N'4',NULL,NULL,N'2023-12-31'),
        (N'45',N'TRESO',NULL,N'Confirmation du solde des emprunts par l''établissement prêteur',N'1',N'ARRETE',NULL,N'5',NULL,NULL,N'2023-12-31'),
        (N'46',N'TRESO',NULL,N'Justificatifs des opérations en rapprochement non dénouées',N'1',N'ARRETE',NULL,N'6',NULL,NULL,N'2023-12-31'),
        (N'47',N'TIERS',NULL,N'État du quittancement de la période',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'48',N'TIERS',NULL,N'Balance âgée des créances locataires',N'1',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'49',N'TIERS',NULL,N'Relevé des encaissements postérieurs à la date d''arrêté',N'1',N'ARRETE',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'50',N'TIERS',NULL,N'État des dépôts de garantie reçus des locataires',N'1',N'ARRETE',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'51',N'TIERS',NULL,N'État des litiges et des garanties de passif, avec la position des conseils',N'1',N'ARRETE',NULL,N'5',NULL,NULL,N'2023-12-31'),
        (N'52',N'FRAIS',NULL,N'Factures de la société de gestion et des prestataires externes',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'53',N'FRAIS',NULL,N'État de calcul de la commission de surperformance',N'0',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'54',N'FRAIS',NULL,N'État détaillé des autres produits et des autres charges par nature',N'1',N'ARRETE',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'55',N'CESSIONS',NULL,N'Acte de cession et décompte définitif du notaire',N'1',N'EVENEMENT',N'461',N'1',NULL,NULL,N'2023-12-31'),
        (N'56',N'CESSIONS',NULL,N'Avis d''opéré et bordereau des frais sur cession de titres',N'1',N'EVENEMENT',N'25',N'2',NULL,NULL,N'2023-12-31'),
        (N'57',N'CESSIONS',NULL,N'État des plus et moins-values réalisées de la période, par actif',N'1',N'ARRETE',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'58',N'CESSIONS',NULL,N'Relevé des frais d''intermédiation et de la commission de mouvement du dépositaire',N'1',N'ARRETE',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'59',N'HB',NULL,N'Promesses d''achat et de vente',N'1',N'EVENEMENT',N'9',N'1',NULL,NULL,N'2023-12-31'),
        (N'60',N'HB',NULL,N'Contrats de promotion immobilière et engagements de souscription non appelés',N'1',N'EVENEMENT',N'9',N'2',NULL,NULL,N'2023-12-31'),
        (N'61',N'HB',NULL,N'État des engagements donnés et reçus à la date d''arrêté',N'1',N'ARRETE',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'62',N'HB',NULL,N'Actes de sûreté réelle, hypothèques, nantissements et cessions Dailly',N'1',N'PERMANENT',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'63',NULL,N'ACCEPT',N'Extrait d''immatriculation au registre du commerce et des sociétés',N'0',N'PERMANENT',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'64',NULL,N'COHERENCE',N'Comptes annuels des quatre exercices précédents',N'1',N'PERMANENT',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'65',NULL,N'COHERENCE',N'Note d''explication des variations établie par la société de gestion',N'1',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'66',NULL,N'COMPTES',N'Historique sur cinq exercices de l''actif net, du nombre de parts, de la valeur liquidative unitaire, des distributions et de la capitalisation',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'67',NULL,N'MAINTIEN',N'Déclaration de la société de gestion sur les changements de forme, de régime et de méthode comptable',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'68',NULL,N'PERMANENT',N'Prospectus de l''OPCI dans la version applicable à l''exercice',N'1',N'PERMANENT',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'69',NULL,N'PERMANENT',N'Règlement de l''OPCI',N'1',N'PERMANENT',NULL,N'2',NULL,NULL,N'2023-12-31'),
        (N'70',NULL,N'PERMANENT',N'Plan de comptes de l''OPCI',N'1',N'PERMANENT',NULL,N'3',NULL,NULL,N'2023-12-31'),
        (N'71',NULL,N'PERMANENT',N'Conventions de gestion, de dépositaire et d''évaluation externe',N'1',N'PERMANENT',NULL,N'4',NULL,NULL,N'2023-12-31'),
        (N'72',NULL,N'PERMANENT',N'Liste des filiales et participations immobilières détenues',N'1',N'PERMANENT',NULL,N'5',NULL,NULL,N'2023-12-31'),
        (N'73',NULL,N'PERMANENT',N'Note des méthodes comptables retenues, méthode par méthode',N'1',N'PERMANENT',NULL,N'6',NULL,NULL,N'2023-12-31'),
        (N'74',NULL,N'PERMANENT',N'Calendrier des arrêtés et périodicité de calcul de la valeur liquidative',N'1',N'PERMANENT',NULL,N'7',NULL,NULL,N'2023-12-31'),
        (N'75',NULL,N'PERMANENT',N'Procès-verbal d''assemblée générale de l''organisme',N'1',N'EVENEMENT',N'102',N'8',NULL,NULL,N'2023-12-31'),
        (N'76',NULL,N'PLANIF',N'Fichier des écritures comptables de la période',N'1',N'ARRETE',NULL,N'1',NULL,NULL,N'2023-12-31'),
        (N'77',NULL,N'PLANIF',N'Balance générale à la date d''arrêté',N'1',N'ARRETE',NULL,N'2',NULL,NULL,N'2023-12-31');
    PRINT 'ref_piece_attendue : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'ref_piece_attendue : deja chargee, rien a faire.';
GO
