-- ref_question_modele : 64 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[ref_question_modele])
BEGIN
    INSERT INTO dbo.[ref_question_modele] ([question_id], [modele_code], [modifie_par], [modifie_le]) VALUES
        (N'4',N'IMMO-RENTE',NULL,NULL),
        (N'9',N'IMMO-RENTE',NULL,NULL),
        (N'11',N'IMMO-EXPERTISE',NULL,NULL),
        (N'12',N'IMMO-EXPERTISE',NULL,NULL),
        (N'13',N'IMMO-EXPERTISE',NULL,NULL),
        (N'14',N'IMMO-EXPERTISE',NULL,NULL),
        (N'15',N'IMMO-EXPERTISE',NULL,NULL),
        (N'18',N'IMMO-RENTE',NULL,NULL),
        (N'19',N'IMMO-RENTE',NULL,NULL),
        (N'20',N'IMMO-RENTE',NULL,NULL),
        (N'21',N'IMMO-CBAIL',NULL,NULL),
        (N'22',N'IMMO-CBAIL',NULL,NULL),
        (N'23',N'IMMO-CBAIL',NULL,NULL),
        (N'25',N'IMMO-LOYERS',NULL,NULL),
        (N'26',N'IMMO-LOYERS',NULL,NULL),
        (N'73',N'IMMO-EXPERTISE',NULL,NULL),
        (N'83',N'PART-ANR',NULL,NULL),
        (N'87',N'PART-ANR',NULL,NULL),
        (N'89',N'PART-ANR',NULL,NULL),
        (N'99',N'PART-CC',NULL,NULL),
        (N'100',N'PART-CC',NULL,NULL),
        (N'134',N'TIERS-AGEE',NULL,NULL),
        (N'136',N'TIERS-AGEE',NULL,NULL),
        (N'166',N'VALO-ECARTS',NULL,NULL),
        (N'168',N'VALO-ECARTS',NULL,NULL),
        (N'181',N'VALO-VL',NULL,NULL),
        (N'182',N'VALO-VL',NULL,NULL),
        (N'204',N'CAP-FRAIS',NULL,NULL),
        (N'205',N'CAP-FRAIS',NULL,NULL),
        (N'215',N'CESS-PMV',NULL,NULL),
        (N'217',N'CESS-PMV',NULL,NULL),
        (N'218',N'CESS-PMV',NULL,NULL),
        (N'249',N'AFF-DISTRIB',NULL,NULL),
        (N'294',N'FIN-INVENT',NULL,NULL),
        (N'299',N'FIN-INVENT',NULL,NULL),
        (N'300',N'FIN-INVENT',NULL,NULL),
        (N'303',N'TRESO-EMPRUNTS',NULL,NULL),
        (N'313',N'TRESO-EMPRUNTS',NULL,NULL),
        (N'355',N'COMPTES-CARACT',NULL,NULL),
        (N'357',N'COMPTES-CARACT',NULL,NULL),
        (N'386',N'FRAIS-SURPERF',NULL,NULL),
        (N'398',N'FRAIS-SURPERF',NULL,NULL),
        (N'408',N'HB-ENGAGE',NULL,NULL),
        (N'409',N'HB-ENGAGE',NULL,NULL),
        (N'411',N'PERM-PLANCPT',NULL,NULL),
        (N'417',N'PERM-PLANCPT',NULL,NULL),
        (N'424',N'AFF-DISTRIB',NULL,NULL),
        (N'425',N'AFF-DISTRIB',NULL,NULL),
        (N'431',N'AFF-DISTRIB',NULL,NULL),
        (N'432',N'AFF-DISTRIB',NULL,NULL),
        (N'433',N'CAP-PARTS',NULL,NULL),
        (N'434',N'CAP-PARTS',NULL,NULL),
        (N'436',N'COHER-VARIAT',NULL,NULL),
        (N'437',N'COHER-VARIAT',NULL,NULL),
        (N'444',N'COHER-VARIAT',NULL,NULL),
        (N'451',N'PART-CC',NULL,NULL),
        (N'452',N'PART-ANR',NULL,NULL),
        (N'463',N'SYN-RAPPRO',NULL,NULL),
        (N'467',N'TIERS-AGEE',NULL,NULL),
        (N'468',N'TRESO-RAPPRO',NULL,NULL),
        (N'469',N'TRESO-RAPPRO',NULL,NULL),
        (N'470',N'TRESO-EMPRUNTS',NULL,NULL),
        (N'477',N'PLANIF-SELECT',NULL,NULL),
        (N'478',N'PLANIF-SELECT',NULL,NULL);
    PRINT 'ref_question_modele : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'ref_question_modele : deja chargee, rien a faire.';
GO
