-- modele_ecriture : 40 ligne(s) de referentiel.
-- Rejouable : la table ne se remplit que si elle est vide. Rien n'est efface.
-- Produit depuis la base de reference, ne pas modifier a la main.

IF NOT EXISTS (SELECT 1 FROM dbo.[modele_ecriture])
BEGIN
    INSERT INTO dbo.[modele_ecriture] ([question_id], [ordre], [compte_num], [sens], [libelle], [source], [modifie_par], [modifie_le]) VALUES
        (N'5',N'1',N'1041',N'DEBIT',N'Frais d''acquisition releves sur l''immeuble entre, exclus du cout d''acquisition',N'Reglement ANC 2021-09, art. 211-3, et art. 411-3 pour le compte 1041.',NULL,NULL),
        (N'5',N'2',N'405',N'CREDIT',N'Contrepartie de la dette au titre des frais d''acquisition',N'Reglement ANC 2021-09, art. 411-3 : compte 405.',NULL,NULL),
        (N'6',N'1',N'1041',N'DEBIT',N'Taxe sur la valeur ajoutee non recuperable sur l''acquisition, incluse dans les frais',N'Reglement ANC 2021-09, art. 211-3 : le cas echeant la TVA non recuperable sur acquisition est incluse dans les frais d''acquisition.',NULL,NULL),
        (N'6',N'2',N'405',N'CREDIT',N'Contrepartie de la taxe non recuperable',N'Reglement ANC 2021-09, art. 411-3 : compte 405.',NULL,NULL),
        (N'82',N'1',N'1041',N'DEBIT',N'Frais d''acquisition du lot de titres entre, tenus hors du cout d''acquisition',N'Reglement ANC 2021-09, art. 212-3.',NULL,NULL),
        (N'82',N'2',N'405',N'CREDIT',N'Contrepartie de la dette au titre des frais d''acquisition des titres',N'Reglement ANC 2021-09, art. 411-3 : compte 405.',NULL,NULL),
        (N'101',N'1',N'661',N'DEBIT',N'Abandon de l''avance en compte courant, constate en moins-value realisee',N'Reglement ANC 2021-09, art. 213-5 : lorsque l''OPCI abandonne son avance en compte courant dans une filiale ou participation, il la comptabilise en resultat, en moins-value realisee.',NULL,NULL),
        (N'101',N'2',N'266',N'CREDIT',N'Sortie de l''actif de l''avance abandonnee, pour le montant abandonne',N'Reglement ANC 2021-09, art. 411-3 : compte 266 Autres creances immobilisees, dont avances en compte courant.',NULL,NULL),
        (N'102',N'1',N'266',N'CREDIT',N'Sortie de l''avance abandonnee pour le montant abandonne',N'Reglement ANC 2021-09, art. 213-5 et art. 411-3, compte 266.',NULL,NULL),
        (N'102',N'2',N'661',N'DEBIT',N'Moins-value realisee correspondant a l''abandon',N'Reglement ANC 2021-09, art. 213-5.',NULL,NULL),
        (N'167',N'1',N'271',N'CREDIT',N'Moins-value latente sur un immeuble maintenu au cout de revient, consecutive a une perte de valeur',N'Reglement ANC 2021-09, art. 211-9, IR3 : dans le cas des immeubles maintenus au cout de revient, la moins-value latente consecutive a une perte de valeur est inscrite directement en difference d''estimation dans un compte de capital.',NULL,NULL),
        (N'167',N'2',N'1052',N'DEBIT',N'Contrepartie en capital de la moins-value latente',N'Reglement ANC 2021-09, art. 211-9, IR3.',NULL,NULL),
        (N'168',N'1',N'271',N'DEBIT',N'Difference d''estimation sur l''immeuble locatif, ecart entre la valeur actuelle et le cout d''acquisition. INVERSER les 2 sens si l''ecart est negatif',N'Reglement ANC 2021-09, art. 211-9 : les differences d''estimation correspondent aux plus ou moins-values latentes sur les immeubles construits et en cours de construction lorsqu''ils sont evalues a la valeur actuelle. Compte 271 du plan de l''article 411-3.',NULL,NULL),
        (N'168',N'2',N'1052',N'CREDIT',N'Contrepartie en capital de la difference d''estimation. INVERSER avec la ligne 1 si l''ecart est negatif',N'Reglement ANC 2021-09, art. 211-9 : elles sont inscrites directement dans un compte de capital. Compte 1052 du plan de l''article 411-3, differences d''estimation sur comptes d''immeubles en cours, construits ou acquis.',NULL,NULL),
        (N'169',N'1',N'271',N'DEBIT',N'Difference d''estimation sur immeuble construit ou en cours. INVERSER les 2 sens si l''ecart est negatif',N'Reglement ANC 2021-09, art. 211-9.',NULL,NULL),
        (N'169',N'2',N'1052',N'CREDIT',N'Inscription directe en compte de capital. INVERSER avec la ligne 1 si l''ecart est negatif',N'Reglement ANC 2021-09, art. 211-9 et art. 411-3.',NULL,NULL),
        (N'175',N'1',N'276',N'CREDIT',N'Revision a la baisse de l''avance en compte courant, portee en differences d''estimation',N'Reglement ANC 2021-09, art. 213-4 : la revision est comptabilisee en differences d''estimation au compte 276 « Difference d''estimation sur autres actifs immobiliers ». Le compte est nomme par l''article lui-meme.',NULL,NULL),
        (N'175',N'2',N'105',N'DEBIT',N'Contrepartie de la revision au compte de variation des differences d''estimation',N'Reglement ANC 2021-09, art. 213-4 : par contrepartie du compte 105. Le compte est nomme par l''article lui-meme.',NULL,NULL),
        (N'176',N'1',N'105',N'DEBIT',N'Contrepartie au compte 105 de la revision de l''avance en compte courant',N'Reglement ANC 2021-09, art. 213-4 : par contrepartie du compte 105.',NULL,NULL),
        (N'176',N'2',N'276',N'CREDIT',N'Difference d''estimation sur autres actifs immobiliers',N'Reglement ANC 2021-09, art. 213-4.',NULL,NULL),
        (N'189',N'1',N'467',N'CREDIT',N'Droits payes par les porteurs pour couvrir les frais d''acquisition et de cession, comptabilises en dettes a la reception',N'Reglement ANC 2021-09, art. 222-2 : ces droits sont comptabilises en dettes lorsqu''ils sont recus par l''OPCI. ATTENTION : l''article ne nomme pas le compte de dettes ; le 467 Autres debiteurs et crediteurs du plan de l''article 411-3 est retenu par choix, non par prescription.',NULL,NULL),
        (N'189',N'2',N'511',N'DEBIT',N'Encaissement des droits payes par les porteurs',N'Reglement ANC 2021-09, art. 411-3 : compte 511 Comptes a vue.',NULL,NULL),
        (N'196',N'1',N'1041',N'DEBIT',N'Frais d''acquisition de l''immeuble, portes en capital hors du cout d''acquisition',N'Reglement ANC 2021-09, art. 211-3 : les frais d''acquisition sont enregistres directement dans un compte de capital, independamment du cout d''acquisition de l''actif. Compte 1041 du plan de l''article 411-3.',NULL,NULL),
        (N'196',N'2',N'405',N'CREDIT',N'Dette envers le prestataire, notaire, agent ou conseil, au titre des frais d''acquisition',N'Reglement ANC 2021-09, art. 411-3 : compte 405 Fournisseurs d''exploitation. Substituer le 511 si le reglement est immediat, ou le 404 si l''actif est en cours.',NULL,NULL),
        (N'197',N'1',N'1041',N'CREDIT',N'Annulation en capital des frais d''acquisition de l''actif cede sur la periode',N'Reglement ANC 2021-09, art. 211-3 : ces frais doivent etre annules dans le compte de capital en contrepartie du resultat de cession, lors de la cession de l''actif. Confirme par l''art. 211-15.',NULL,NULL),
        (N'197',N'2',N'761',N'DEBIT',N'Imputation des frais d''acquisition annules sur le resultat de cession. REMPLACER par le compte 661 si la cession degage une moins-value',N'Reglement ANC 2021-09, art. 211-14 : la plus ou moins-value de cession est enregistree nette des frais encourus tant a l''acquisition qu''a la cession. Le sens depend du resultat, que le modele ne prejuge pas.',NULL,NULL),
        (N'198',N'1',N'1041',N'DEBIT',N'Frais d''acquisition du lot de titres, portes en capital hors du cout d''acquisition',N'Reglement ANC 2021-09, art. 212-3 : les frais d''acquisition de titres sont enregistres directement dans un compte de capital, independamment du cout d''acquisition de l''actif.',NULL,NULL),
        (N'198',N'2',N'405',N'CREDIT',N'Dette au titre des frais d''acquisition des titres',N'Reglement ANC 2021-09, art. 411-3 : compte 405.',NULL,NULL),
        (N'199',N'1',N'1041',N'CREDIT',N'Annulation en capital des frais d''acquisition des titres cedes sur la periode',N'Reglement ANC 2021-09, art. 212-3 : lors de la cession ces frais sont annules dans le compte de capital en contrepartie du resultat de cession.',NULL,NULL),
        (N'199',N'2',N'761',N'DEBIT',N'Contrepartie au resultat de cession des titres. REMPLACER par le compte 661 en cas de moins-value',N'Reglement ANC 2021-09, art. 212-3.',NULL,NULL),
        (N'201',N'1',N'467',N'DEBIT',N'Solde du compte de dettes des droits payes par les porteurs, a mesure que les frais sont engages',N'Reglement ANC 2021-09, art. 222-2 : le compte de dettes est solde par la contrepartie d''un compte de commissions en capital lorsque les frais sont engages. Le compte de dettes n''est pas nomme par l''article.',NULL,NULL),
        (N'201',N'2',N'1031',N'CREDIT',N'Compte de commissions en capital, contrepartie du solde du compte de dettes',N'Reglement ANC 2021-09, art. 222-2, et art. 411-3 : compte 1031 Commissions de souscription.',NULL,NULL),
        (N'219',N'1',N'761',N'DEBIT',N'Couts directement attribuables a la cession, imputes avec la plus-value realisee. REMPLACER par le compte 661 en cas de moins-value',N'Reglement ANC 2021-09, art. 211-15 : les couts directement attribuables a cette cession sont imputes avec la plus ou moins-value realisee et donc portes en diminution du prix de cession.',NULL,NULL),
        (N'219',N'2',N'405',N'CREDIT',N'Dette envers le prestataire au titre des frais de cession',N'Reglement ANC 2021-09, art. 411-3 : compte 405. Substituer le 511 si le reglement est immediat.',NULL,NULL),
        (N'220',N'1',N'1041',N'CREDIT',N'Annulation en capital des frais d''acquisition de l''actif cede',N'Reglement ANC 2021-09, art. 211-15 : par ailleurs les frais d''acquisition enregistres initialement en capital doivent etre annules en contrepartie du resultat de cession.',NULL,NULL),
        (N'220',N'2',N'761',N'DEBIT',N'Contrepartie au resultat de cession. REMPLACER par le compte 661 en cas de moins-value',N'Reglement ANC 2021-09, art. 211-15 et 211-14.',NULL,NULL),
        (N'223',N'1',N'661',N'DEBIT',N'Abandon d''avance en compte courant comptabilise en resultat, en moins-value realisee',N'Reglement ANC 2021-09, art. 213-5.',NULL,NULL),
        (N'223',N'2',N'266',N'CREDIT',N'Sortie de l''avance abandonnee',N'Reglement ANC 2021-09, art. 411-3, compte 266.',NULL,NULL),
        (N'252',N'1',N'1291',N'DEBIT',N'Acompte verse au titre de l''exercice sur le resultat net, porte en capitaux propres',N'Reglement ANC 2021-09, art. 321-5 : les acomptes verses au titre de l''exercice sont comptabilises dans un compte de capitaux propres. Compte 1291 du plan de l''article 411-3, acomptes sur resultat net de l''exercice.',NULL,NULL),
        (N'252',N'2',N'511',N'CREDIT',N'Reglement de l''acompte par le compte a vue',N'Reglement ANC 2021-09, art. 411-3 : compte 511 Comptes a vue.',NULL,NULL);
    PRINT 'modele_ecriture : ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' ligne(s) chargee(s).';
END
ELSE PRINT 'modele_ecriture : deja chargee, rien a faire.';
GO
